- README.md
- lab/Laboratory.vue
- lab/experiments/ActionBar.vue
- lab/experiments/ActionBarTest/index/Modal.vue
- lab/experiments/Button.vue
- lab/experiments/KitchenSink.vue
- lab/experiments/StackedModals/index/FirstModal.vue
- lab/experiments/StackedModals/index/FirstModal/SecondModal.vue
- package-lock.json
- package.json
- src/components/Button/README.md
- src/components/Input/README.md
- src/components/Notice/src/Notice.vue
- src/components/Select/src/SelectControl.vue
- src/components/Stepper/src/Stepper.vue
some icons were off (wrong size or wrong style, i.e. outlined instead of filled)
- removes `orbit-icons`
- adds `maker-icons`: https://github.com/square/maker-icons
> fix: removes orbit-icons, uses better maker-icons

- styleguide/App.vue
Modal and Blade demos in styleguide were impossible to use because the syntax highlighting of prismjs forced source code to appear above the opened Modals/Blades, this PR comments out the problematic styles
> docs: comment out problematic styles

- package.json
- src/components/SegmentedControl/src/SegmentedControl.vue
Got a reported error case with the failed-to-validate logic firing even in seemingly correct uses of the component and its child component, gonna disable it for now to see if that fixes things.
> Disable segmentedcontrol validation

- .eslintrc.js
- .gitignore
- README.md
- build/deploys/ensure.js
- build/deploys/pull.js
- build/deploys/push.js
- build/sync-to-latest/index.js
- package-lock.json
- package.json
deploying styleguide and lab was an ad-hoc process that only I understood
adds scripts which auto-deploys the lab and styleguide after lab and styleguide builds respectively. everything should work auto-magically even if the person has never done a deploy before. also automatically copies versioned styleguide releases to a `latest` branch so we have a stable URL, i.e. `square.github.io/maker/styleguide/latest`, that we can share with people and will always have the latest updates.
> docs: Auto deploy + latest deploy

- package.json
- src/components/ActionBar/src/InlineActionBar.vue
BX noticed some weird issues with actionbars used within modals on mobile safari and tracked it down to the `margin-bottom` style inside inlineactionbar, the fix is to switch to `padding-bottom`.
> fix: Inline margin to padding

- package.json
- src/components/Stepper/README.md
- src/components/Stepper/src/Stepper.vue
Added size variations to stepper component
https://www.figma.com/file/2cgnI0Cb5L7DqdCNiIRrot/%F0%9F%8D%81-Maker-Design-System?node-id=2379%3A19590
- Small stepper size uses small buttons, and primary button type
- Medium and large buttons use medium and large buttons respectively, and use secondary button type
> feat: update stepper to include a size slot

- package.json
- src/components/ActionBar/src/ActionBarButton.vue
- src/components/ActionBar/src/InlineActionBar.vue
- src/components/Modal/src/Modal.vue
- src/components/Modal/src/ModalLayer.vue
- src/utils/transitions.js
Modal breakpoint of 1200px was too large.. it was decided to reduce this to 840px
Reduced breakpoints from 1200px to 840px for modals, the inline-action-bar, and the transition variable.
I left the atomic action bar and action bar layer at 1200px since those breakpoints were unrelated to modals specifically.
> style: update modal breakpoint

- package.json
- src/components/ActionBar/src/ActionBarLayer.vue
- src/components/ActionBar/src/AtomicActionBar.vue
- src/components/ActionBar/src/InlineActionBar.vue
🚀 🚀 🌔 🌔 
Increases ActionBar bottom padding to 58px on mobile to partially evade iOS Safari deadclick zone. Leaves desktop at 32px.
> fix: this actionbar is GOING TO DA MOON

- src/components/Input/README.md
Props section is now generated but Input docs had old props section left over from before
Removed old props section heading
> docs(input): remove double props section

- package.json
- src/components/ActionBar/src/ActionBarLayer.vue
- src/components/ActionBar/src/AtomicActionBar.vue
- src/components/ActionBar/src/InlineActionBar.vue
Deadclick on Safari still easily occurs unless you tap the very top of the button
Increased ActionBar bottom padding to 64px on mobile to fix deadclick on Safari
> fix: Increase ActionBar padding on mobile

- src/components/ActionBar/README.md
- src/components/ActionBar/src/ActionBarButton.vue
- src/components/Modal/README.md
- src/components/Modal/src/Modal.vue
- src/components/Modal/src/ModalLayer.vue
We need the ability to close the modal on ESC key press
Added `closeOnEsc` prop
`closeOnEsc` isn't supported on the stacked modal
> feat(actionbar): add window.esc to add ability to close modal on ESC

- src/components/ActionBar/src/ActionBarLayer.vue
- src/components/ActionBar/src/AtomicActionBar.vue
people complained about empty padding at the bottom of their sites when no actionbar is present
removes padding from actionbarlayer when actionbar is not present
nope
> fix: hides actionbarlayer padding if actionbar not present

- src/components/ActionBar/src/ActionBarLayer.vue
- src/components/ActionBar/src/AtomicActionBar.vue
Action bar buttons were flickering and had border/outline around the buttons while loading the modal on mobile devices
Added `-webkit-transform: translate3D(0, 0, 0)`. See: https://stackoverflow.com/questions/10134935/weird-css3-transition-flickering
> fix(actionbar): actionbar buttons flickering

- src/components/ActionBar/src/ActionBarButton.vue
1. Main text on the default button was being cut off w/o `...` at the end
2. Need `stack` align style updates
> fix(actionbar): stack align styles and truncate main text

- .github/workflows/release.yml
- package.json
The release build was happening prior to publish, so it wasn't using the correct version for the CSS class names
For example, v4.1.4 uses class name [`.\1F4DA 0-0-0-semantic-releasevs3NG1`](https://unpkg.com/@square/maker@4.1.4/components/Button/styles.css)
This was happening because the `npm run build` script was happening prior to bumping the version in `package.json`. According to [semantic-release docs](https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that-requires-the-package-jsons-version) it should happen in the versioning cycle.
Move the build script to the `prepublishOnly` hook, which should have the new version env var.
Reference: https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that …
> ci: move build to prepublish

- .github/workflows/deploy-styleguide.yml
- .github/workflows/release.yml
- build/deploys/ensure.js
- build/deploys/pull.js
- build/deploys/push.js
- build/generate-deploy-index/index.js
- build/sync-to-latest/index.js
- build/utils.js
- styleguide/webpack-styleguide-config.js
runs styleguide deploys after semantic releases in CI
no screenshots
maybe it works or maybe it doesn't, there's no way of knowing until we merge into master
note to future self: if it doesn't work it's probably because the github checkout action does not check out tags along with the head commit, so look into that if this fails
> ci: perform styleguide deploy after semantic release

- src/components/Checkbox/src/CheckboxControl.vue
- src/components/Input/src/InputControl.vue
- src/components/Notice/README.md
- src/components/Notice/index.js
- src/components/Notice/src/Notice.vue
- src/components/Notice/src/NoticeButton.vue
- src/components/Radio/src/RadioControl.vue
- src/components/Select/src/SelectControl.vue
- src/components/Textarea/src/TextareaControl.vue
- src/components/Toggle/src/ToggleControl.vue
- src/utils/BlockFormControlLayout/src/BlockFormControlLayout.vue
Notice refresh
- updates Notice status colors (including the Error status color which is updated across all components)
- adds NoticeButton child component to be used with Notice
https://square.github.io/maker/styleguide/notice-refresh/#/Notice
none
> feat: Notice refresh

- src/components/Modal/README.md
- src/components/Modal/src/Modal.vue
- src/components/Modal/src/ModalLayer.vue
Modals cannot be closed when you click outside of them.
Add the ability to pass in an options object on modal open, with a parameter to close modals when you click outside of them
> feat(modal): close modal on click outside and before close hook

- src/components/Modal/README.md
- src/components/Modal/src/Modal.vue
- src/components/Modal/src/ModalLayer.vue
With the latest changes to modals there was another container div introduced in the modal layer component, this container was not styled and therefor causes issues on mobile.
Added styling to the modal layer container.
> fix(modal): mobile modals not styled correctly

- .github/workflows/deploy-styleguide.yml
- .github/workflows/lint-code.yml
- .github/workflows/release.yml
- build/deploys/pull.js
- build/deploys/push.js
- build/generate-deploy-index/index.js
- build/sync-to-latest/index.js
- build/utils.js
- styleguide/webpack-styleguide-config.js
The bash session was not existing when a command failed
Set the [`-e` flag](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html#:~:text=exit%20immediately%20if%20a%20pipeline%20(see%20pipelines)%2C%20which%20may%20consist%20of%20a%20single%20simple%20command%20(see%20simple%20commands)%2C%20a%20list%20(see%20lists)%2C%20or%20a%20compound%20command%20(see%20compound%20commands)%20returns%20a%20non-zero%20status.) so that errors thrown in the bash session are propagated.
> ci: bash to exit on error

- src/components/Modal/src/ModalLayer.vue
Certain child elements of modals were incorrectly triggering modals to close.
`Node.contains` relies on the fact that the element that was clicked is contained within the DOM of the modal. If the following example of code were to be inside of a modal:
```
<span
v-if="display"
@click="display = !display"
>
testing
</span>
```
Whenever the span is clicked, it toggles itself off of the DOM. The click event propagates up to the ModalLayer and the `.contains` logic checks if the span is inside or outside of the modal. Given that the element is no longer in the DOM the modal layer closes the current modal.
While this kind of issue can be stopped at the source using `click.stop` or `v-show` instead of a v-if, I believe that it is easy to imagine more complex implementations of this logic that …
> fix(modal): use better logic to decide whether a click is inside of a modal or not

- src/components/ActionBar/README.md
- src/components/ActionBar/src/AtomicActionBar.vue
The action bar container does not let pointer events through to the layer behind. This is particularly noticeable in situations where the primary action is not visible. This PR allows for pointer events to go through the container but not the buttons.
> feat(action-bar): allow clicking through action bar container

- src/components/ActionBar/src/ActionBarLayer.vue
- src/components/ActionBar/src/AtomicActionBar.vue
- src/components/ActionBar/src/InlineActionBar.vue
- src/components/Heading/README.md
- src/components/Text/README.md
ios 15.0 adds an erratic address bar in mobile safari that constantly changes window height as user scrolls up or down the page
implements apple's recommended fix, which is to use the `env(safe-area-inset-bottom)` CSS variable.
I haven't actually tested this yet... I don't have a physical device which runs iOS 15.0 and I don't have iOS 15.0 as an option in any of the available supported devices inside Simulator. I think to be able to emulate a iOS 15.0 device in Simulator you would need to download and install Xcode 13+ (currently in beta?), which also requires macOS 11..3+. I'm still on macOS 10.x and prefer not to switch to 11.x yet so maybe someone else can test this for me? 🙃
> fix: actionbar bottom padding on ios 15.0

- src/utils/InlineFormControlLayout/src/InlineFormControlLayout.vue
Same as #96 but rebased off of master.
Form controls (e.g. Radio, Checkbox) have a hardcoded `color` attribute (previously `rgba(0, 0, 0, 0.9)`), making labels and sublabels difficult to see on dark backgrounds.
Form controls now inherit the `color` attribute.
When placed in `<div style="background-color:black; color:white">`:
> feat(form-controls): inherit text color

- .github/CONTRIBUTING.md
- package-lock.json
- package.json
[semantic-release/commit-analyzer](https://github.com/semantic-release/commit-analyzer) was using the angular preset by default, which doesn't support the `!` syntax for breaking change.
Since we follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) standard, the preset has been set to `conventionalcommits`.
> ci: specify conventional commits for release

- src/components/Container/README.md
- src/components/Container/index.js
- src/components/Container/src/Container.vue
- src/components/Section/README.md
- src/components/Section/src/Section.vue
- Simplify design of Section component to remove dropshadow
- Provide a transition for existing scenarios with Section and move to a new component called Container
> feat(container): move section component to new container component

- src/components/Stepper/src/Stepper.vue
The quantity inside the Stepper currently has a hardcoded text color. It is not very visible on darker backgrounds.
The Stepper inherits the text color.
Other similar changes may be needed on other Form controls when theming is introduced.
> fix(stepper): inherit text color

- src/components/Container/src/Container.vue
The Container component's sublabel and requirement label styles were using `var(--color-black-55)` which would not match non-black text colors. Additionally, the var was not redefined when moving from the previous iteration, the Section component, so the text color was just black.
The sublabel and requirement label now match the Section's text color. They also work with passed-in text colors (not black).
> fix(container): sub/requirement labels missing opacity

- src/components/Select/src/SelectControl.vue
The fill color was previously `rgba(0, 0, 0, 0.05)`, which was not visible on dark backgrounds. 
Changed the fill color to a specific grey color, rather than a low-opacity black.
In a similar fashion, we may want to change the outline variant's colors; it currently is white with a black outline. However, it may make more sense to use something like
- background color: inherit or transparent;
- outline color: inherit text color (for contrast)
> fix(select): change fill variant color

- src/components/Input/src/InputControl.vue
- src/components/SegmentedControl/src/SegmentedControl.vue
- src/components/Textarea/src/TextareaControl.vue
The Input, SegementedControl, and Textarea components' fill variant all used a low-opacity black `rgba(0, 0, 0, 0.05)` as the fill color. This does not show up on black backgrounds.
Before
After
There are still a couple of instances of `rgba(0, 0, 0, 0.05)` used in maker, particularly for disabled variants. I didn't want to go ahead and change all of these, since I wanted design to weigh in on it first. However, I went ahead and changed default state colors since we made this change already for Select. #103
> fix(controls): changed background color from low-opacity black

- lab/App.vue
- lab/create-router.js
- lab/experiments/index.vue
- lab/webpack-lab-config.js
The lab app root was being nested (eg, another app instance was being inserted into the root app). This isn't a big deal, just created an unnecessary double-`div`.
- Removed App.vue nesting
- Made `router-view` a root component
- Made all routes root-routes (since it's no longer nested)
> refactor(lab): removed redundant nested root app

- src/components/Container/src/Container.vue
The requirement label was too light. See #112
Before:
After:
bumped the opacity from 0.55 -> 0.7 as a temporary fix before theming is available.
> fix(container): increase sub/requirement label opacity

- src/components/Container/README.md
- src/components/Container/src/Container.vue
On website, the `requirement label` was wrapping on overflow. However, it is typically pretty short, so we want it not to wrap, and to have the the `label` accommodate to that size instead.
- ~~Added a `no-wrap` prop that would~~ make the `requirement label` not wrap ~~for its usage in website~~.
- Added `--space` between the `label` and `requirement-label` so that they are not touching
Before:
After:
> fix(container): make requirement label no-wrap

- build/webpack-development-config.js
- Linting errors were failing and blocking Webpack development build iterations
- Every time dev build is initialized, it would lint all files and be slow
- Prevent linting errors from blocking builds. It will still error but not block build iterations.
- Only lint new files. This means it won't lint on startup.
> build(dev): only lint new files and dont fail on error

- .github/workflows/release.yml
semantic-release v18 requires node v14 but our repo uses node v12 so we need to pin semantic-release to ^17
what the title says
nope
> ci: pin semantic-release to v17

- build/generate-deploy-index/index.js
See #124
- use [semver `sort`](https://github.com/npm/node-semver/blob/master/functions/sort.js) to sort version numbers
- replace regex check with semver `valid` to check version numbers
> build: sort deploy versions using semver sort

- src/components/ProgressBar/README.md
- src/components/ProgressBar/index.js
- src/components/ProgressBar/src/ProgressBar.vue
Closes #136 
This PR introduces a reusable progress bar component. It has 2 styles (square and rounded/pill), is colour configurable, and 4 different sizes.
The `ProgressBar` component has 4 main inputs:
- `shape`: is either square or rounded/pill (sites that have rounded or pill designs will have the same progress bar shape)
- `color`: controls the color of the inner bar
- `size`: xsmall (4px), small (8px), medium (12px), or large (16px)
- `progress`: a 0-100 number that controls the display of the inner bar
The inner progress bar is a full width bar that uses a transform to match the progress input. It does this instead of a width for performance reasons, as animating width is not nearly as performant.
> feat(progress-bar): add progress bar component

- src/components/Button/src/TextButton.vue
- src/components/Container/README.md
- src/components/Container/src/Container.vue
closes https://github.com/square/maker/issues/88
TL;DR: people can now put icons into the labels and sublabels of containers
described in issue above, also view here: https://square.github.io/maker/styleguide/mcontainer-slots/#/Container
no
> feat(container): label & sublabel slots

- .eslintrc.js
- lab/experiments/ActionBarTest.vue
- lab/experiments/ActionBarTest/CartModal.vue
- lab/experiments/ActionBarTest/index.vue
- src/components/Modal/src/Modal.vue
- src/components/TouchCapture/index.js
- src/components/TouchCapture/src/TouchCapture.vue
PR for drag/swipe to dismiss functionality on mobile modals as prototyped below.
- Modal is only swipe/draggable in mobile
- `on-swipe-down` is a single point touch event, min 30px in distance, max 300ms in duration. It closes the Modal
- `on-drag-down` is a single point touch even
- `on-drag-end` is the end of a drag event. Modal closes if it's been dragged more than 30% client height. Otherwise it bounces back into place.
- Touch to dismiss events only work when Modal is scrolled to the top. When modal is scrolled up/down, there's a 800ms delay before dismiss events are active again.
- The distance/timing thresholds  swipe events can be adjusted, as can the minimum drag to close
Design:
Lab:
https://square.github.io/maker/lab/swipe-dismiss/#/ActionBarTest
> feat(modal): add drag/swipe to dismiss on mobile modals

- lab/experiments/ActionBarTransition.vue
- lab/experiments/ActionBarTransition/ItemModal.vue
- lab/experiments/ActionBarTransition/index.vue
- src/components/ActionBar/src/InlineActionBar.vue
- src/utils/transitions.js
This PR adds a delayed bouncy spring up transition to the inline action bar, as well as a lab experiment to preview different delay/stiffness/damping/mass values for the transition.
- `ActionBarTransition`: experiment to demo inline action bar spring transition values
- `transitions`: add  `springUpBounceFn` and `springDownBounceFn` for the new default inline action bar transitions
- `InlineActionbar`: add `enterAnimation`, `leaveAnimation`, and `enterDelay` props
> feat(inline-action-bar): delayed spring transition

- src/components/ActionBar/README.md
- src/components/ActionBar/src/ActionBarLayer.vue
- src/components/ActionBar/src/AtomicActionBar.vue
- src/components/ActionBar/src/InlineActionBar.vue
https://github.com/square/maker/issues/169
Adjusted padding to be the desirable 24px all the way around (original design intent)
Simplified the padding calculations with the [env()](https://developer.mozilla.org/en-US/docs/Web/CSS/env())
Added fallbacks in case env isn't supported.
Previously we had a significant amount of extra padding added to get around the nefarious Safari "deadclick" zone. The usage of the env safe zone should have resolved that, but it looks some of those calculations resulted in roughly the same less than ideal positioning. Tested thoroughly on desktop + mobile on Chrome and Safari. Even did a built test on our PWA version:
> fix(actionbar): adjust padding to be 24 and include env inset calc

- src/components/Modal/src/ModalLayer.vue
This PR fixes an issue where modals would be able to close if a popover layer was not present.
Closes #192 
The fix is to add an optional chaining operator to `vm.popoverApi?.closePopover()` in the modal layer's `close` method, as well as set a default value for `PopoverApiKey` injection in the modal layer.
> fix(modal): fix modals closing if popover layer is missing

- .github/workflows/deploy-styleguide.yml
- .github/workflows/lint-code.yml
- .github/workflows/release.yml
Previously, GitHub's official Node.js action, `setup-node` did not support reading from `.nvmrc` so we had to use a custom bash instance to use nvm to setup node.
However, they recently added support for  [`node-version-file`](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file) which means we can go back to using `setup-node`.
`setup-node` is GitHub's [official recommendation](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python#specifying-the-node.js-version) for installing a specific version of Node.js.
- Use `setup-node` with `node-version-file`
Will follow up with a dependency caching PR
> ci: use setup-node with node-version-file

- lab/experiments/ContentAnimateIn.vue
- src/components/TransitionStaggered/README.md
- src/components/TransitionStaggered/index.js
- src/components/TransitionStaggered/src/TransitionStaggered.vue
- src/utils/transitions.js
This PR adds a transition group component that allows for staggered list transitions.
- `ContentAnimation`: experiment to demo the staggered transition
- `transitions`: add  `springSubtle`, `toSubtleFloatyY` constants and `staggeredFloatUpFn` for the designed transition that accepts a stagger
- `TransitionStaggered`: transition group component that takes a stagger item count by viewport and passes back a function to calculate the load index.
For a mobile stagger count of 1 item at a time and desktop stagger count of 4 at a time:
> feat(transition-staggered): staggered transition

- lab/experiments/ActionBarTest/index.vue
- src/components/Modal/src/Modal.vue
- src/components/TouchCapture/src/TouchCapture.vue
This PR addresses the previously observed bug where dragging the modal also dragged the underlying site on mobile Safari.  This produces an unwanted visual effect and can also cause the page to reload.
Bug:
https://user-images.githubusercontent.com/1486885/145483791-21495336-b1cc-46ce-a146-965f6b3a6f89.mov
Fix:
https://user-images.githubusercontent.com/1486885/145483830-456e08c0-6c19-4bcc-8b7c-bb6b6b579af5.mov
> fix(modal): fix background site drag for modal on safari

- .eslintrc.js
- lab/experiments/ActionBarTest.vue
- lab/experiments/ActionBarTest/CartModal.vue
- lab/experiments/ActionBarTest/index.vue
- lab/experiments/ActionBarTransition.vue
- lab/experiments/ActionBarTransition/ItemModal.vue
- lab/experiments/ActionBarTransition/index.vue
- lab/experiments/ContentAnimateIn.vue
- src/components/ActionBar/src/ActionBarLayer.vue
- src/components/ActionBar/src/InlineActionBar.vue
- src/components/Modal/src/Modal.vue
- src/components/TouchCapture/index.js
- src/components/TouchCapture/src/TouchCapture.vue
- src/components/TransitionStaggered/README.md
- src/components/TransitionStaggered/index.js
- src/components/TransitionStaggered/src/TransitionStaggered.vue
- src/utils/transitions.js
This PR combines previously reviewed components and changes for the Transitions release, including:
- Modal swipe or drag to close functionality on mobile using the `TouchCapture` component
- New `springUpBounceFn` and `springDownBounceFn` transitions on the default and inline action bar
- New `TransitionStaggered` component that takes a row count and item index and animates in item with a delay
> feat(transitions): transitions changes for modal, actionbar and staggered transition

- src/components/Modal/src/Modal.vue
Fix for this Sentry error when page is scrolled before modal is finished rendering.
https://sentry.io/organizations/square-inc/issues/2860398335/
> fix(modal): fix type error when page is scrolled before modal finishes rendering

- src/components/Dialog/README.md
- src/components/Dialog/src/DialogLayer.vue
See https://github.com/square/maker/issues/207
This PR adds two configurable options to the Dialog component when opening it via the dialog API.
1. `closeOnClickOutside` - If a click is captured on the dialog layer that is not contained within the dialog content slot, then the dialog will close. Default is false.
2. `beforeCloseHook` - This function gets called before a dialog closes out. The Dialog will only proceed to close if the this hook function returns true
> feat(Dialog): Add closeOnClickOutside option to the Dialog component

- lab/experiments/ActionBarTransition/ItemModal.vue
- src/components/ActionBar/src/ActionBarLayer.vue
- src/components/ActionBar/src/AtomicActionBar.vue
- src/components/ActionBar/src/InlineActionBar.vue
Action bar is missing on iOS Chrome when a page opens in a new tab. (body height is not consistent when open in a new tab vs reload) 
I added `--chrome-bottom-offset` to the action bars and let the app calculate the offset and set the extra space to the action bar.
Few people were having similar issue:
https://stackoverflow.com/questions/65086394/sticky-element-doesnt-work-properly-in-ios-chrome
https://stackoverflow.com/questions/65282211/chrome-on-iphone-overflows-content-on-empty-page-on-new-tab-only-not-reload
https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser
> refactor(actionbar): Add --chrome-bottom-offset to bottom padding

- lab/experiments/ActionBarTransition/ItemModal.vue
- src/components/ActionBar/src/ActionBarLayer.vue
- src/components/ActionBar/src/AtomicActionBar.vue
- src/components/ActionBar/src/InlineActionBar.vue
https://github.com/square/maker/pull/209 had wrong commit type so it was reverted
This reverts https://github.com/square/maker/pull/211 and put back https://github.com/square/maker/pull/209
This is a temporary fix for https://github.com/square/maker/issues/201 and `--chrome-bottom-offset` will be set in MTheme in the future
> fix(actionbar): temp fix for chrome ios; add --chrome-bottom-offset to padding

- src/components/Checkbox/src/CheckboxControl.vue
- src/components/ImageUploader/src/ImagePicker.vue
- src/components/Input/src/InputControl.vue
- src/components/Radio/src/RadioControl.vue
- src/components/Select/src/SelectControl.vue
- src/components/Textarea/src/TextareaControl.vue
This PR fixes the fallback styles for form inputs used without an MTheme wrapper.
Without fallbacks:
With fallbacks:
> fix(theme): fix color fallbacks on form components without MTheme

- src/components/Heading/README.md
- src/components/Heading/src/Heading.vue
- src/components/Text/README.md
- src/components/Text/src/Text.vue
no prop to customize text alignment in MText & MHeading
adds `textAlign` prop to MText & MHeading which supports values: `inherit`, `left`, `right`, `center`
nope
> feat: adds text-align prop to MText & MHeading

- src/components/Heading/README.md
- src/components/Heading/src/Heading.vue
- src/components/Text/README.md
- src/components/Text/src/Text.vue
no prop to uppercase all text in MText & MHeading (needed for website)
adds `textTransform` prop which supports the values: `inherit`, `none`, `uppercase`
nope
> feat: text-transform prop for MText & MHeading to uppercase text

- src/components/Card/src/Card.vue
Adds theme styles for card components inside am MTheme wrapper.
Before:
White bg, gray border, inherited color.
After:
Theme bg, Neutral 20 border, inherited (theme) color.
> feat(card): add theme styles to card

- lab/experiments/ActionBarButtons.vue
- src/components/ActionBar/src/ActionBarButton.vue
This fixes https://jira.sqprod.co/browse/MAKER-43
Bug:
Fixed:
Other alignments and wrapping styles are not impacted by this change:
https://square.github.io/maker/lab/actionbarbutton-align/#/ActionBarButtons
> fix(actionbarbutton): center align for main and label text

- src/components/Dialog/src/Dialog.vue
- src/components/Dialog/src/DialogLayer.vue
- src/components/Theme/src/default-theme.js
In a lot of places on website, dialog and modal are used in similar contexts. Dialog should be themeable to apply the same styles to both.
> feat(dialog): maker theme support for dialog

- src/components/Dialog/src/Dialog.vue
- src/components/Dialog/src/DialogLayer.vue
Forgot to add the styles computed prop to the dialog template. Also, limited the `position: fixed` on Dialog's `disableScroll` class to phone/tablet displays. Adding the style to body on desktop can cause site width to collapse.
> fix(dialog): add style variables to dialog template

- src/components/Dialog/README.md
- src/components/Heading/README.md
- src/components/Heading/src/Heading.vue
- src/components/Text/README.md
- src/components/Text/src/Text.vue
We occasionally need individual components to opt out of Maker Text / Maker Heading's scale-based `size` prop and internal `line-height` calculations. E.g. Site Logo, etc. Slack conversation [here](https://square.slack.com/archives/C02NYVDM0JU/p1646860034936189) for context.
Adds a lineHeight and a fontSize prop to Maker Text and Maker Heading. These are directly applied as inline styles on the element, overriding the `font-size` and `line-height` CSS rules that are calculated in the `style` tag and applied via a class.
No other information sorry
> feat: add fontSize and lineHeight props 

- src/components/Input/src/InputControl.vue
As discussed in #244, `MInput`'s internal `<input>` has `border-radius: inherit`, causing it to take on the `border-radius` of its container and clip text at the start and end of the input, even though the `<input>` has no visible border.
This PR simply removes the `border-radius: inherit` directive.
> fix(input): remove invisible border radius

- src/components/Stepper/src/Stepper.vue
Removes default `shape` prop on to enable theme props to apply.
> fix(stepper): remove default stepper shape to enable theming

- src/components/ActionBar/README.md
- src/components/ActionBar/src/ActionBarButton.vue
See #248.
- Makes ActionBarButton disabled when loading. This was already added to Button and TextButton in #250.
- also added a loading example in the ActionBar styleguide
> fix(action-bar-button): make ActionBarButton disabled when loading

- src/components/Dialog/src/DialogLayer.vue
Fixes dialog layer bug on desktop. Typically, adding `position: fixed` causes the body to collapse if its contents are not as wide as the viewport. This `position: fixed` style is needed on mobile devices in order to use Dialog with the PinInput component but this resets the position on desktop.
> fix(dialog): fix position bug on desktop dialog layer

- .browserslistrc
- package-lock.json
https://github.com/square/maker/issues/226#issuecomment-1071061425
Drops support for UC Browser 12.12 and Opera Mini browsers so that our `:focus-within` CSS styles within the MInput component work again.
This has been broken since v4.1.0 when [this line](https://github.com/square/maker/compare/v4.0.1...v4.1.0#diff-43302d1852d8010ee012aab4dda2d01abb664e11f73617fe625f2ba112a958edR3) was released 🤦
> fix(input)!: focus states by dropping support for UC & Opera Mini

- src/components/TextButton/src/TextButton.vue
https://github.com/square/maker/issues/252
https://github.com/square/maker/issues/254
- Changed line-height to 1.5 which reflects the 24px line height for a font-size of 16px from Figma
- Removed outline:none in order to support having a visible outline when button is focused via tabbing
> fix(text-button): Fix line-height and accessibility outline

- src/components/Text/README.md
- src/components/Text/src/Text.vue
- The text component supports a limited amount of sizes
- When using the text component, there are scenarios where the `element` could be a null value preventing default rendering.
- Adds all supported sizes. duplicating from the Heading component
- Adds conditional for element rendering in case of a `null` value.
This replicates work that happened in this PR https://github.com/square/maker/pull/263, but which had some rebase issues and triggered a major release. Due to that rebase / revert I couldn't cherry-pick -- original author of this work is @bashunaimiroy
> feat(text): add support for all text sizes

- src/components/Popover/README.md
- src/components/Popover/src/PopoverContent.vue
Adds theme colors to popover styles.
> feat(popover): add theme colors to popover styles

- .github/workflows/release.yml
I tried backporting a bugfix from v9 to v8 but the release action never ran: https://github.com/square/maker/pull/281#issuecomment-1087768768
i think it's because i didn't read github docs closely enough. I thought `*` meant _"match zero or more of the **preceeding** character"_ which is what it means in regex... but how github interprets it as is _"match zero or more of **any** character"_ 🤦 .
fixes the github branch filtering syntax so that it hopefully works this time
nope
> ci: fix github branch filtering syntax for release job

- src/components/Choice/README.md
- src/components/Choice/src/Choice.vue
- src/components/Choice/src/ChoiceOption.vue
When introducing the `disabled` field on the choice provider, reactivity was broken and prevented UI updates from selections/prop changes. This PR adds a small refactor to move selection/disabled handling to the provider.
> fix(choice): fix reactivity of choice => choice option

- lab/experiments/Popover.vue
- src/components/Popover/src/PopoverContent.vue
Changes to Popover color styles as well as lab to demo them.
> fix(popover): update popover color styles

- lab/experiments/ThemeTest.vue
- lab/experiments/Themes/preview.vue
- src/components/ActionBar/src/ActionBarButton.vue
- src/components/Button/src/Button.vue
- src/components/Calendar/src/Calendar.vue
- src/components/Card/src/Card.vue
- src/components/Checkbox/src/CheckboxControl.vue
- src/components/Choice/src/Choice.vue
- src/components/Choice/src/ChoiceOption.vue
- src/components/Container/src/Container.vue
- src/components/Dialog/src/DialogLayer.vue
- src/components/Divider/src/Divider.vue
- src/components/ImageUploader/src/ImagePicker.vue
- src/components/ImageUploader/src/ImageSelection.vue
- src/components/Input/src/InputControl.vue
- src/components/Modal/src/ModalLayer.vue
- src/components/Notice/src/Notice.vue
- src/components/PinInput/src/PinInput.vue
- src/components/Popover/src/PopoverContent.vue
- src/components/Radio/src/RadioControl.vue
- src/components/SegmentedControl/src/Segment.vue
- src/components/SegmentedControl/src/SegmentedControl.vue
- src/components/Select/src/SelectControl.vue
- src/components/Skeleton/src/SkeletonBlock.vue
- src/components/Skeleton/src/SkeletonText.vue
- src/components/Stepper/src/Stepper.vue
- src/components/TextButton/src/TextButton.vue
- src/components/Textarea/src/TextareaControl.vue
- src/components/Theme/src/Theme.vue
when an app uses maker it can be confusing to tell which css vars are maker's or the app's 
prefixes maker's public css vars with `maker-`
if you used any `--neutral` vars in your app prefix them with `--maker-color-neutral` and if you used any other css vars prefix them with `--maker`
> refactor!: prefix public css vars

- src/components/Notice/src/Notice.vue
When notice component was used in a theme with the block variant it was always gray.
The notice background color has the incorrect CSS property fallback, setting to a neutral color (when used in the theme) as the default.
Removes the neutral color as the primary css property, instead relying on the color-bg variable set in each of the notice types. It's always there so don't need to have a fallback.
This wasn't caught in doc dev testing for the notice since there's no theme to set the neutral colors. We should consider setting up some testing environments with doc dev to easily switch between a theme context and no theme context.
> fix(notice): background color for variant block

- lab/experiments/ThemeTest.vue
- lab/experiments/Themes/preview.vue
- lab/experiments/Themes/utils/colors.js
- src/components/ActionBar/src/ActionBarButton.vue
- src/components/Button/src/Button.vue
- src/components/Calendar/src/Calendar.vue
- src/components/Choice/src/Choice.vue
- src/components/Container/src/Container.vue
- src/components/Menu/README.md
- src/components/PinInput/src/PinInput.vue
- src/components/SegmentedControl/src/SegmentedControl.vue
- src/components/Stepper/src/Stepper.vue
- src/components/TextButton/src/TextButton.vue
- src/components/Textarea/src/TextareaControl.vue
- src/components/Theme/README.md
- src/components/Theme/src/Theme.vue
- src/components/Theme/src/default-theme.js
reaching team alignment, using more generic names in our global theme config for typography related stuff
renames `title` to `heading` and `paragraph` to `body`, also updates some docs
https://square.github.io/maker/styleguide/some-font-color-renames/#/Theme
> refactor!: some font-related config renames

- src/components/Menu/README.md
- src/components/PinInput/README.md
- src/components/PinInput/src/PinInput.vue
https://github.com/square/maker/issues/229
pininput overflows container instead of shrinking, this looks bad and make the pininput almost unusable
makes pininput shrink if it can't fit within its container
nope
> fix(pininput): makes pininput shrink if it doesn't fit container

- src/components/PinInput/README.md
- src/components/PinInput/index.js
- src/components/PinInput/src/PinInputControl.vue
- src/components/PinInput/src/PinInputFormItem.vue
makes pininput code more standard compared to the other block form items in maker
refactors pininput to use blockformcontrollayout internally
nope
> refactor(pininput): uses blockformcontrollayout internally now

- lab/experiments/ThemeTest.vue
- src/components/ActionBar/src/ActionBarButton.vue
- src/components/Button/src/Button.vue
- src/components/Calendar/src/Calendar.vue
- src/components/Card/README.md
- src/components/Card/src/Card.vue
- src/components/Choice/src/ChoiceOption.vue
- src/components/Image/README.md
- src/components/Image/src/Image.vue
- src/components/ImageUploader/src/ImagePicker.vue
- src/components/ImageUploader/src/ImageSelection.vue
- src/components/Input/src/InputControl.vue
- src/components/Notice/src/Notice.vue
- src/components/PinInput/src/PinInput.vue
- src/components/Popover/src/PopoverContent.vue
- src/components/ProgressBar/README.md
- src/components/ProgressBar/src/ProgressBar.vue
- src/components/SegmentedControl/README.md
- src/components/SegmentedControl/src/Segment.vue
- src/components/SegmentedControl/src/SegmentedControl.vue
- src/components/Select/src/SelectControl.vue
- src/components/Skeleton/src/SkeletonText.vue
- src/components/Stepper/src/Stepper.vue
- src/components/TextButton/src/TextButton.vue
- src/components/Textarea/src/TextareaControl.vue
- src/components/Theme/README.md
- src/components/Theme/src/Theme.vue
- src/components/Theme/src/default-theme.js
Alternative shapes theming approach, a pared down alternative to [314](https://github.com/square/maker/pull/314).
- No shape aliases
- Adds image border radius as a `shapes` property and as a visible Maker variable.
Adds theming support for shape across multiple maker components.
1. Defines a `shapes` prop on default theme where global shape presets and their border radius values are defined:
```
shapes: {
defaultBorderRadius: '4px',
buttonBorderRadius: '4px',
imageBorderRadius: '0px',
},
```
2. Adds global maker border radius variables to Theme to be used by components that don't have a local `shape` prop override and for use to apply shape similarly to our color variables:
- `--maker-shape-default-border-radius`
- `--maker-shape-button-border-radius`
- …
> feat(shape): theme support for shapes

- src/components/PinInput/src/PinInputControl.vue
- src/components/Stepper/README.md
- src/components/Stepper/src/Stepper.vue
- src/utils/constants.js
Setting a stepper input to a much higher or lower number requires tapping the `+`/`-` buttons many times to get to the correct value.
Closes #317
This PR adds the ability to manually type in a value for a stepper in order to side step having to tap the increment/decrement buttons many times.
Clicking/tapping the inner number will create an input that will autofocus and (for mobile) pop open the numeric keyboard.
Manual inputs are validated to be an actual number and be within the min/max range (if defined).
The updated value will not be emitted until the user blurs/hits enter.
https://user-images.githubusercontent.com/3402466/167197148-ad631c88-7ff0-4418-ab46-7a3a991bfeac.mov
> feat(stepper): allow manual number entry for stepper

- lab/README.md
previous major release failed since v10 was already published (& removed) from npm and once a version has been published to it can't be replaced or unpublished sooo we need to hop, skip, and jump to v11
> feat(docs)!: need breaking commit to get to v11 since v10 is already taken

- src/components/Checkbox/src/CheckboxControl.vue
- src/components/Input/src/InputControl.vue
- src/components/PinInput/src/PinInputControl.vue
- src/components/Popover/src/PopoverContent.vue
- src/components/Radio/src/RadioControl.vue
- src/components/Select/src/SelectControl.vue
- src/components/Textarea/src/TextareaControl.vue
The Maker color renaming for v. 11 broke some styles on form inputs that were relying on the old `--color-background` and `--color-text` properties.
Bug:
Fix:
> fix(colors): fix colors on form components

- .github/workflows/deploy-styleguide-lab.yml
- .github/workflows/deploy-styleguide.yml
- .github/workflows/release.yml
- build/generate-deploy-index/index.js
- build/sync-to-latest/index.js
- build/utils.js
- lab/webpack-lab-config.js
- package.json
- styleguide/webpack-styleguide-config.js
- no auto lab deploys for PRs or releases
- same comment with link to styleguide and lab deploy is re-commented every time a commit is pushed to an open PR
- deploy index is totally unstyled
- adds auto lab deploys for all PRs and releases
- comment with links should only be commented once
- adds some style to deploy index
we can [change this line](https://github.com/square/maker/pull/330/files#diff-dfea2822e411012ccce10fd935556cbbdf9659c52be2de78ef8f83ac3b127155R39) from `pretzelhammer/comment-on-pr` back to `unsplash/comment-on-pr` once this issue is closed https://github.com/unsplash/comment-on-pr/issues/55 and/or this PR is merged https://github.com/unsplash/comment-on-pr/pull/56
> ci: auto Lab deploys for PRs & releases

- src/components/Select/src/SelectControl.vue
Select components with the `required` attribute set are automatically applying the invalid styling, even on first load if the default value is a placeholder.
Applies invalid styling with our custom `invalid` prop rather than the `:invalid` selector.
> fix(select): fix styling for invalid prop

- src/components/Image/README.md
- src/components/Image/src/Image.vue
The current and upcoming shapes conversion work needs Images to support a `shape` prop that supports either `square`, `circle` or `arch` as values.
Updates the local `shape` property on Image to support the following values:
- `square` - this resets the border-radius set by the theme's `shapes.imageBorderRadius` value to `0`
- `circle` - this applies a border radius equal to the image element's height (per designs)
- `arch`- this applies a border radius equal to the image element's height to the top left/right corners of the image
- MImage's `shape` prop has changed:
- grep your codebase for `<m-image` and/or `shape="` to find all instances that may need to be migrated and then:
- `squared` value has been renamed to `square` (and should be migrated to `square`)
- `pill` has been removed …
> feat(image)!: update shape property for image

- src/components/Image/README.md
- src/components/Image/src/Image.vue
Adds an `original` image shape option to reset an image within a theme.
> fix(image): add original shape option for images

- lab/experiments/ThemeTest.vue
- src/components/Image/src/Image.vue
- src/components/Theme/src/Theme.vue
We don't currently limit the size of MTheme's `shapes.imageBorderRadius`. For small thumbnail images, a border radius of 10px or more can be overwhelming.
This PR limits the image border radius to `8px` max on all smaller (150px and below) thumbnail images.
Before with `shapes.imageBorderRadius: 16px`
After with `shapes.imageBorderRadius: 16px`, thumbnail border radius limited to `8px`
> feat(image): clamp border radius for thumbnail images

- package-lock.json
- package.json
- src/components/Notice/src/Notice.vue
need parity with square-icons, all square-icons are colored using `fill` and not `color` or `stroke`
the main change in this PR is bumping maker-icons from 2.1.2 to 3.0.0, and the pr for that is here: https://github.com/square/maker-icons/pull/14
tldr: we trace all icons now (like square-icons does) so that we can color all icons (including outlined ones) using `fill`
nope
> fix(notice): colors icons using fill, required for parity with square-icons

- src/components/Icon/src/Icon.vue
- src/components/Notice/src/Notice.vue
i found a slightly better fix that builds on top of this pr: https://github.com/square/maker/pull/353 😆 
now icons can be colored with `color` css and that's more intuitive than using `fill`, and it still works with maker-icons and square-icons which use `fill`.
adds `fill: currentColor` to the `.Icon` css class in the icon component
nope
> fix(icon): can color icon with color css now

- src/components/Image/src/Image.vue
Release [v11.6.0](https://github.com/square/maker/releases/tag/v11.6.0) introduced a bug to the image shape class.
This PR fixes the image shape class.
> fix(image): fix image shape class

- src/utils/maker-colors.js
Using an the `@square/maker` import alias in `src/utils/maker-color.js` seems to have caused a build error.
Changing the `get-contrast.js` import on `maker-colors.js` to a relative import seems to fix the build error, after testing with https://github.com/square/maker/tree/fix-import-built
> fix(maker-colors): fix contrast util import on maker-colors util

- src/components/Image/src/Image.vue
Fixes images being loaded at full size instead of the corresponding sizes attribute passed in.
Add the sizes attribute when creating the image element for loading.
> fix(image): fix loading proper size image

- src/components/TransitionResize/src/TransitionResize.vue
- src/utils/TransitionCollapse/README.md
- src/utils/TransitionCollapse/index.js
- src/utils/TransitionCollapse/src/TransitionCollapse.vue
- src/utils/transitions.js
need collapse transition component in Maker for next component: Accordion
adds TransitionCollapse utility component
i'd like to move all the transition components from the `components` dir to the `utils` dir which is why I placed TransitionCollapse there in the first place
> feat: adds MTransitionCollapse utility component, for use in MAccordion later

- src/components/Button/src/Button.vue
- src/components/TextButton/src/TextButton.vue
Updates the loading component to use the same color as the text-button and fix the opacity to be 1.
Text button:
Loading state before fix:
Loading state after fix:
> fix(text-button): use button color for loading, and keep opacity at 1

- src/components/Input/src/InputControl.vue
- src/components/Select/src/SelectControl.vue
- src/components/Textarea/src/TextareaControl.vue
Autofill styles currently look strange and inset on Input components.
This PR fixes the autofill styles and applies Maker colors.
> fix(input): fix webkit autofill styles

- styleguide/COMPONENTS.md
- styleguide/INDEX.md
- styleguide/SideNav.vue
- styleguide/UTILS.md
- styleguide/create-router.js
- styleguide/webpack-styleguide-config.js
components in the `utils` directory were not being documented in the styleguide
components in the `utils` directory will now be documented in the styleguide
check out the new styuleguide side nav: https://square.github.io/maker/styleguide/styleguide-utils/#/
after this gets merged i wanna move all the Transition components and the TouchCapture component from the `components` directory to the `utils` directory
> docs: adds utils to styleguide

- src/components/Calendar/src/Calendar.vue
Selected date is not visible in dark background
> fix(calendar): selected text color not visible in dark theme

- src/components/Dialog/src/Dialog.vue
- src/components/Dialog/src/DialogLayer.vue
- src/components/Modal/src/Modal.vue
https://github.com/square/maker/issues/397
Adds scroll handling and actionbar anchoring on longer, scrolling mobile dialogs.
> fix(dialog): fix actionbar on scrolling dialogs

- src/components/Button/README.md
- src/components/Theme/src/default-theme.js
if selected primary color is white and background color is white secondary & tertiary pattern buttons become invisible
changes default theme styles to use contextual colors for buttons
https://square.github.io/maker/styleguide/more-button-contrast/#/Button
> feat: more contrast for default theme'd secondary & tertiary buttons

- src/components/ProgressBar/README.md
- src/components/ProgressBar/src/ProgressBar.vue
- src/components/Theme/src/default-theme.js
progressbar wasn't themeable or context-aware (would become invisible on black backgrounds because the default color of the progressbar is black)
progressbar is now themeable and context-aware (progressbar flips to white on background backgrounds since its default color is now set to @colors["neutral-100"]
https://square.github.io/maker/styleguide/themeable-progressbar/#/ProgressBar
> feat: makes progressbar themeable

- src/components/StarRating/README.md
- src/components/StarRating/src/Star.vue
- src/components/StarRating/src/StarRating.vue
- src/components/Theme/src/default-theme.js
star rating was not context aware
star rating is now context aware, it's default color was `#ffbf00` which is the same as `@colors.warning.fill`, so i changed it to `@colors.warning.fill` so the default behavior against a white background is the same but the star rating will now change colors to improve contrast against certain backgrounds (before it just always stayed `#ffbf00` and just became unreadable or invisible)
nope
> feat(starrating): is now context aware

- src/components/Image/README.md
- src/components/Image/src/Image.vue
Currently, there is no way of knowing when the `<img>` element in an `MImage` component is not only loaded but has completed it's fade-in transition.
This PR adds a `image:loaded` event that is emitted when the image src is loaded and the `@after-enter` hook on the image transition is called.
> feat(image): add image:loaded event

- src/components/TextButton/README.md
- src/components/TextButton/src/TextButton.vue
textbutton was never designed to have an :active state and it should have never been added in the first place, same goes for the over-eager :focus state, and padding inherited from browser native styles
removes the :active state, removes the browser native padding, and changes the :focus style to :focus-visible, also adds small :hover state (simple subtle opacity change)
also slightly improves the textbutton styleguide docs: https://square.github.io/maker/styleguide/fix-textbutton/#/TextButton
> fix(textbutton): removes active state & padding, changes focus to focus-visible

- src/components/Accordion/src/Accordion.vue
The Accordion header has some padding due to the browser defaults for the `button` element, as well as some spacing below the `title` slot from the text element for the `secondary` slot, even when there's no slot content.
This PR resets the default button padding so accordion header's contents are flush with their container and conditionally renders  the text element for secondary slot.
> fix(accordion): fix spacing in accordion header

- lab/experiments/ThemeTest.vue
- src/components/ProgressBar/src/ProgressBar.vue
the original plan for this PR was just to add a few more components to the ThemeTest lab but while doing that I ran into a small MProgressBar bug where its background container color wasn't responsive to the theme background color, and so along with updating the ThemeTest lab i also fixed that bug in this PR
fixes ProgressBar container background color contrast bug against dark backgrounds
https://square.github.io/maker/lab/more-components-in-themetest/#/ThemeTest
> fix(progressbar): bg color on dark site backgrounds

- src/components/Theme/src/default-theme.js
originally i set the default progresscircle color to the contextual primary fill color BUT progressbar uses neutral-100 as the default and i think that makes more sense and also for the sake of consistency i wanted both progress components to have similar defaults so i switched progresscircle's default color to neutral-100
changes progresscircle's default color to neutral-100 to be more consistent with progressbar
nope
> fix(progresscircle): make default color same as progressbar

- lab/experiments/ButtonTruncation.vue
- src/components/TextButton/README.md
- src/components/TextButton/src/TextButton.vue
TextButton's overflowing content gets cut off
Adds `truncateText` prop to TextButton for situations where long text should be truncated with an ellipsis.
> feat(textbutton): add text truncation option

- build/deploys/push.js
if pushing a styleguide or lab deploy failed during CI it would fail silently which makes it hard to find in the github UI, this updates the script to fail loudly when a push fails
> ci: fail loudly when deploys push fails

- src/components/Accordion/README.md
- src/components/Accordion/src/Accordion.vue
Accordion header does not have side slots
Adds side slots to the Accordion header.
> feat(accordion): add side slots to accordion header

- src/components/Image/src/Image.vue
The `image:visible` event was only firing for new images and not cached images
Emits the `image:visible` event for both new and cached images.
> fix(image): fix image:visible event for cached images

- src/components/Accordion/README.md
- src/components/Blade/src/BladeLayer.vue
- src/components/Dialog/src/DialogLayer.vue
- src/components/Modal/src/ModalLayer.vue
the injected api keys for the layer components aren't working in Website for whatever bizarre reason... it might be that there's a subtle difference between how our dev webpack config (which builds local dev, the styleguide, and the lab) from our prod webpack config (which builds & bundles the components for use in prod) resolves api key symbol imports.
some screenshots of some stacktraces
and
reverts absolute imports back to relative imports
i have no clue or idea how or why this would fix the issue, this is basically a shot in the dark
> fix: layer api key imports

- lab/experiments/ThemeTest.vue
- src/components/Notice/README.md
- src/components/Notice/src/Notice.vue
- src/components/Theme/src/default-theme.js
Notice only accepts theme icons and does not have a primary variant.
Adds an icon slot and primary variant for Notice.
> feat(notice): add icon slot and primary variant

- src/components/Choice/README.md
- src/components/Choice/src/Choice.vue
Wrapping the Choice container introduced a breaking change in the component behavior when the Choice component was used in a parent Carousel component and users of Choice were explicitly relying on Choice NOT to wrap.
Adds `wrapChoices` as a prop so wrapping of Choice options can be turned on/off.
> fix(choice): add wrapChoices prop

- lab/experiments/ThemeTest.vue
- src/components/Theme/src/default-colors.js
- src/utils/maker-colors.js
- changes default primary color from `#000000` to `#006aff` (so styleguide examples look better)
- this will not have any impact on our end users, all of which use the Theme component in their apps and already explicitly override the primary color
- updates corresponding derived contextual primary colors as well
- also will not impact our end users for the same reasons as above
- changes default overlay color from `rgb(0, 0, 0, 0.3)` to `rgb(0, 0, 0, 0.32)` (as this is what was being computed and set by maker-colors.js)
- also will not impact our end users for the same reasons above
- updates maker-colors.js to assume the primary color is `#006aff` instead of `#000000` is none is provided (so it matches the default theme)
- assuming end users already updated their code from …
> refactor!: changes primary default color from #000 to #006aff

- lab/experiments/ThemeTest.vue
- src/components/ActionBar/src/ActionBarButton.vue
- src/components/Button/src/Button.vue
- src/components/Notice/README.md
- src/components/Notice/src/Notice.vue
Notice's `variant` prop did not function like any other `variant` prop on any other component, so we're renaming it to `display` since it functions more like the CSS `display` property
in answer above
this is a breaking change and all users of maker will have to grep their codebase for `<m-notice variant="block">` and `<m-notice variant="inline">` and change them to `<m-notice display="block">` and `<m-notice display="inline">` respectively.
> refactor(notice)!: renames variant prop to display

- src/components/Menu/README.md
- src/components/Menu/src/Menu.vue
- src/components/Menu/src/MenuOption.vue
Emit events when Menu is opened or closed, which are currently not available
* Add `menu:open` and `menu:close` emitted when implemented `Popover` component is opened or closed
* Add `option:click` event when a `MenuOption` component is clicked or enter is pressed
> feat(menu): add open and close events for menu, click events for menu-option

- .github/workflows/deploy-styleguide-lab.yml
- .github/workflows/release.yml
- .github/workflows/remove-styleguide-lab.yml
- build/deploys/pull.js
- build/deploys/push.js
- build/generate-deploy-index/index.js
- package.json
- styleguide/INDEX.md
so the deploy styleguide & lab job already had a very high success rate, the only times it would fail is if multiple instances of the job were run in parallel, in which case the first job to finish would complete successfully but all of the following jobs would fail because they would attempt to push their changes to remote but remote had changes that they didn't have locally so they would fail to push their changes and thus the job as a whole would fail
adds a `git pull --rebase` right before the `git push` to increase the success rate of the job, it'll still sometimes fail, but in general should fail much much less often as the pushes of independent jobs rarely conflict with each other and can be auto-merged
also, while poking around, i also made some CSS improvements to the Maker …
> ci: increase deploy styleguide & lab job success rate

- src/components/Stepper/src/Stepper.vue
backports this pr https://github.com/square/maker/pull/450 which was released on 15.x to 14.x
> fix(stepper): clicking off manual input without changing value now works (#450)

- src/components/Image/src/Image.vue
backport of this approved PR back to the 14.x major line: https://github.com/square/maker/pull/458
> fix(image): relative src, sizes, & srcset attribute ordering (#458)

- lab/App.vue
- src/components/Dialog/README.md
- src/components/Dialog/src/DialogLayer.vue
calling `dialogApi.close` may or may not close the dialog, and there was no way for the caller to know whether or not the dialog was actually closed
`dialogApi.close` now returns `true` if the close was successful and `false` otherwise
also i updated the dialog docs and made them a little bit better
also i removed the close-popover-in-dialog-nexttick bandage fix since the underlying problem has been solved in an earlier pr
nope
> feat(dialog): return success/failure from close fn

- lab/App.vue
- lab/components/MultiModal.vue
- lab/experiments/CloseAllModals.vue
- src/components/Modal/README.md
- src/components/Modal/src/Modal.vue
- src/components/Modal/src/ModalLayer.vue
The bugs:
❌ (1) a beforeClose hook set via options would never run
One way to set a beforeClose hook was via the options object in the 2nd param of `modalApi.open`, e.g.
```js
this.modalApi.open(
// 1st param, render function
() => <MyModal />,
// 2nd param, modalApi options object
{
beforeCloseHook: () => console.log('I will never run 🤦'),
},
);
```
This is bad obviously because the whole purpose of the beforeClose hook is to potentially block the modal from closing if the user forgot or failed to do something, but it would close regardless potentially leading to bad user experience or data in a corrupt or incomplete state. The beforeClose hook technically could also be used to perform final data clean up steps after a user was done interacting with a modal, and it failing to run could …
> fix(modal): closing bugs

- lab/experiments/CloseAllModals.vue
- src/components/Choice/src/Choice.vue
- src/components/Container/src/Container.vue
- src/components/Icon/src/Icon.vue
- src/components/Menu/src/Menu.vue
- src/components/Modal/src/Modal.vue
- src/components/Modal/src/ModalLayer.vue
- src/components/Notice/src/Notice.vue
- src/components/TextButton/src/TextButton.vue
- src/components/Theme/src/utils.js
- src/utils/InlineFormControlLayout/src/InlineFormControlLayout.vue
some of our users were mounting MModals outside of MModalLayers which... is not a use-case we ever anticipated but now have to deal with, hence this PR. any time a MModal was mounted outside of an MModalLayer an error would get thrown, however most of these errors are harmless, so we should silence the harmless ones and only emit errors when there are real errors that can damage the behavior of the app.
mounting a MModal outside of an MModalLayer will now not emit an error... UNLESS an explicit `beforeClose` prop is set on the MModal, since that prop requires the presence of an MModalLayer to function correctly, so an error will get emitted then
see console in: https://square.github.io/maker/lab/layerless-modals/#/CloseAllModals
> fix(modal): fail loudly if Modal w/beforeClose prop is mounted outside of a ModalLayer

- src/components/Button/README.md
- src/components/Button/src/Button.vue
- src/components/Theme/src/default-theme.js
Currently `MButton`'s `textPattern` prop is not themeable.
Makes `MButton`'s `textPattern` prop themeable.
> fix(button): make textPattern themeable

- src/components/Divider/README.md
- src/components/Divider/src/Divider.vue
- src/components/Theme/src/default-theme.js
divider was a skinny boi but users wanted divider to be a T H I C C boi
adds themable `color` and `size` props to Divider, can now be made thicker and lighter or darker, as the user pleases
https://square.github.io/maker/styleguide/gaps/#/Divider
> feat(divider): themable color & size props

- lab/experiments/ThemeTest.vue
- src/components/Button/src/Button.vue
- src/components/TextButton/README.md
closes https://github.com/square/maker/issues/471
https://stackoverflow.com/a/64039674/2766908
adds `padding-bottom: 0.5em` to `.TruncateText` class in MButton and cancels it out with `margin-bottom: -0.5em`. link: https://github.com/square/maker/pull/480/files#diff-a63a381a9ca0c90e9b1158a50b1c4bfbb0cb75b95488098dba716e13324c2342R628-R632
other changes in PR are minor style refactors that are unrelated to the fix
screenshot proof that fix works:
> fix(button): cutoff descenders

- src/components/Accordion/README.md
- src/components/ActionBar/README.md
- src/components/Blade/README.md
- src/components/Button/README.md
- src/components/Dialog/README.md
- src/components/Input/README.md
- src/components/Menu/README.md
- src/components/Modal/README.md
- src/components/PinInput/README.md
- src/components/Popover/README.md
- src/components/Select/src/SelectControl.vue
- src/components/Toast/README.md
- src/utils/Row/README.md
- src/utils/Row/src/Row.vue
- src/utils/Transition/README.md
- src/utils/TransitionCollapse/README.md
- src/utils/TransitionFadeIn/README.md
- src/utils/TransitionResponsive/README.md
- src/utils/TransitionSpringLeft/README.md
- src/utils/TransitionSpringUp/README.md
- src/utils/TransitionStack/README.md
1. poor contrast for custom icons in Row, Accordion, Select
2. normalizes buttons & background colors across examples in all readmes
1. commit: https://github.com/square/maker/pull/483/commits/fdea470c0008f37c86be86377043c481a12be402
2. commit: https://github.com/square/maker/pull/483/commits/aaa299ec84693105e65f3abb9b32a47cb37e30f2
affected components:
- Row: https://square.github.io/maker/styleguide/custom-icons-contrast/#/Row
- Accordion: https://square.github.io/maker/styleguide/custom-icons-contrast/#/Accordion
- Menu: https://square.github.io/maker/styleguide/custom-icons-contrast/#/Menu
> fix: custom icons having poor contrast in Row, Accordion, Select

- src/components/Container/src/Container.vue
When there's no header content, `MContainer` still renders an empty header wrapper.
Render no header wrapper if there's no header content.
> feat(container): stop rendering header when there's no header content

- lab/experiments/ThemeTest.vue
- src/utils/maker-colors.js
Our current contextual colors are not as optimized against colorful MTheme backgrounds as they are against black and white backgrounds.
Some design-suggested changes to the contextual color logic for colorful backgrounds.
> fix(theme): update contextual colors

- src/components/Button/src/Button.vue
The padding/margin-bottom fix for button text being cut off can sometimes result in misalignment, when the `margin: 0` style of MText is loaded after `margin-bottom: 0` and receives precedence.
Adds `!important` property to the padding/margin styles for the button text fix.
> fix(button): enforce bottom padding, margin on truncated text

- .github/CODEOWNERS
- .github/CONTRIBUTING.md
- .github/MIGRATION.md
- .github/WHAT_IS_MAKER.md
- README.md
docs could have used an improvement
(1) adds a **Quick links** section to the [main readme](https://github.com/square/maker/blob/more-docs/README.md):
(2) Adds **Create an issue first** and **Maker Team heirarchy** to the [contributing docs](https://github.com/square/maker/blob/more-docs/.github/CONTRIBUTING.md):
(3) adds [migration docs](https://github.com/square/maker/blob/more-docs/.github/MIGRATION.md):
> docs: better docs for first time users & contributors

- src/components/Checkbox/src/CheckboxControl.vue
- src/components/Input/README.md
- src/components/Input/src/InputControl.vue
- src/components/PinInput/README.md
- src/components/PinInput/src/PinInputControl.vue
- src/components/Radio/src/RadioControl.vue
- src/components/Select/README.md
- src/components/Select/src/SelectControl.vue
- src/components/Textarea/README.md
- src/components/Textarea/src/TextareaControl.vue
- src/components/Theme/src/publicize-vars.js
- src/components/Toggle/src/ToggleControl.vue
error colors in a lot of form components were not contextual
makes error color in all form components contextual
affected components:
- [checkbox](https://square.github.io/maker/styleguide/contextual-invalid-forms/#/Checkbox)
- [input](https://square.github.io/maker/styleguide/contextual-invalid-forms/#/Input)
- [pininput](https://square.github.io/maker/styleguide/contextual-invalid-forms/#/PinInput)
- [radio](https://square.github.io/maker/styleguide/contextual-invalid-forms/#/Radio)
- [select](https://square.github.io/maker/styleguide/contextual-invalid-forms/#/Select)
- [textarea](https://square.github.io/maker/styleguide/contextual-invalid-forms/#/Textarea)
- [toggle](https://square.github.io/maker/styleguide/contextual-invalid-forms/#/Toggle)
> fix: contextual error color for form components

- src/components/Container/README.md
- src/components/Container/src/Container.vue
Container padding cannot be customized
Added new padding prop to Container component. Updated docs.
> feat(container): add padding prop to container component

- lab/experiments/ButtonCustomization.vue
- src/components/Button/README.md
- src/components/Button/src/Button.vue
- src/components/Theme/src/default-components.cjs
Button currently does not support hover text styles.
Adds a `textPatternHover` prop to Button, removes MText from inside button in favor of directly applying text pattern styles.
> feat(button): add hover text pattern support

- .github/MIGRATION.md
- src/components/Thumbnails/README.md
- src/components/Thumbnails/src/Thumbnails.vue
before thumbnails `size` prop only accepted a Number, and converted it to pixels, for setting the thumbnail size... now it accepts any valid CSS string (similar to most props on most Maker components)
`size` prop now accepts any valid css value for width/height
https://square.github.io/maker/styleguide/css-sizes-for-thumbnails/#/Thumbnails
> feat(thumbnails)!: allows any valid css size for size prop

- src/components/Theme/src/utils.cjs
We noticed that in our app that the entire lodash lib was being pulled into our main script which seemed curious because we use the "babel-plugin-lodash". Some digging revealed this dependency was coming from Maker.
In the .cjs file if you import via `require('lodash')` it imports the entire lib, as the `babel-plugin-lodash` appears to only only handles ES. Have to import via the individual functions and now we longer have the entire lodash lib.
> fix(theme): allow webpack to properly treeshake lodash

- styleguide/App.vue
- styleguide/SideNav.vue
styleguide looked kinda ugly <1000px viewport width, the main issue being that the sidenav is kinda fat and doesn't collapse at all
makes sidenav collapse on <1000px viewport width, gets toggle buttons to open it (similar to the theming controls toggle buttons)
click and resize window <1000px width: https://square.github.io/maker/styleguide/reponsive-nav/#/
> docs: responsive styleguide side nav

- styleguide/COMPONENTS.md
- styleguide/SideNav.vue
- styleguide/create-router.js
components in styleguide sidenav aren't grouped/categorized/organized in any way
adds groups/categories for components
https://square.github.io/maker/styleguide/sidenav-groupings/#/
> docs: group components in styleguide sidenav

- src/components/ImageUploader/src/ImageSelection.vue
close button in imageuploader component wasn't an mbutton
it's now an mbutton, and will respond to shape theming
https://square.github.io/maker/styleguide/themable-button-in-imageuploader/#/ImageUploader
> fix(imageuploader): close button now responsive to shape theming

- src/components/Textarea/README.md
- src/components/Textarea/src/TextareaControl.vue
Browsers automatically apply the `:invalid` pseudoclass to empty textareas that are `required`. This goes against our styling for text inputs where `:invalid` is only triggered when the prop is explicitly set to true, such as when errors are returned for an attempted form submission.
Aligns invalid textarea behavior with text inputs. Red border only applies when `invalid` prop/attribute is set to true.
> fix(textarea): fix invalid state style

- src/components/Button/src/Button.vue
Button hover color get's lightened or darkened slightly even it's a custom value.
No longer lighten/darken hover color if it's different than the main button fill color.
> fix(button): don't change a custom button hover color

- src/components/Image/README.md
- src/components/Image/src/Image.vue
* `object-fit` style is originally set to `cover` which will clip the provided image to the specified image dimensions. This allows the image to be scaled to the given dimensions in addition
* Specify `object-fit` property on the image
* Adds `contain` and `scale-down` object fit properties. `cover` is treated as the default
https://user-images.githubusercontent.com/82115556/212120973-382c6c62-4613-49bf-b6ec-febae3f3dfec.mov
> feat(image): add object-fit property to image component

- src/components/Card/README.md
- src/components/Card/src/Card.vue
- src/components/Image/src/Image.vue
- src/components/Popover/README.md
- src/components/Popover/src/PopoverContent.vue
- src/components/Theme/src/default-components.cjs
No cards with glass backdrop.
Adds the `variant` prop to Cards, and styles for the `glass` variant. Renames current default card style to `outline` and makes it the theme default. Adds examples for usage to style guides.
> feat(cards): add glass variant for cards, rename default to outline

- build/webpack-base-config.js
- src/components/Pill/README.md
- src/components/Pill/src/Pill.vue
We have a project where we'd like to use `MPill` to present informational items, however we'd like to be able to customise the shape of the pill.
This PR adds the `shape` property, accepting either a single shape or a tuple of two shapes to use on each endcap.
I've implemented this with the `::before` and `::after` pseudo-elements but I'm not overly fond of this implementation. That being said, I couldn't think of a better way to do it without manually `clip-path`ing the entire capsule uniquely for every pair of shapes.
There's also an ancillary change to let Webpack process `style` tags with the `lang` explicitly set to `postcss`. This doesn't have any actual changes on the build, but fixes syntax highlighting and context-aware tools in editors like VSCode using Volar.
> feat: add `shape` property to `MPill`

- src/components/Image/README.md
- src/components/Image/src/Image.vue
* `object-position` is currently set to `center`, regardless of `object-fit`
* add `objectPosition` property to adjust image `object-position`
https://user-images.githubusercontent.com/82115556/215611988-078fa337-8b09-4dcb-bdaf-9e4385d748e7.mov
> feat(image): add object-position property to image

- .github/MIGRATION.md
- lab/components/AsyncInlineSvg.vue
- lab/components/HtmlFragment.vue
- lab/experiments/CustomIcons.vue
- src/components/Icon/src/Icon.vue
- src/components/Theme/src/default-components.cjs
- src/components/Theme/src/default-icons.cjs
described in migration notes in this pr:
> Before to theme icons you'd have to pass Vue components to the MTheme config object. This had two big limitations: icon components must be compiled either ahead of time or on the fly, and it wasn't possible to customize the prop values on the icon component, it would always be rendered with the defaults. Furthermore, doing this just for icon components was a little odd since we already established the pattern of using render functions for all other components which conditionally render nested content, e.g. MModals, MDialogs, MBlades, MToasts. Now to theme icons you use render functions, which solves all of the problems noted above.
also, while not mentioned in the migration notes (since it's not a breaking change) this PR also adds the ability to …
> refactor(icon)!: render fns instead of vue components

- src/components/TouchCapture/src/TouchCapture.vue
Some events are not cancelable such as scrolling. We try to cancel theses events even though browser's wont' let us leading to an error in the console which is picked up by error monitoring.
To replicate go to: 
https://www.justonemoreplantco.com/events-and-workshops
Click "Philadelphia Flower Show Bus Trip" to bring up the modal scroll down a bit then try to drag all the way down
https://user-images.githubusercontent.com/16027039/223269826-6500fc2b-e74f-4dd8-a660-e7a5c59e1b56.mov
No UI changes only we should check if an event is cancelable before we actually try to cancel it.
> fix(touchcapture): stop generating noisy console error

- src/components/PinInput/src/PinInputControl.vue
Closes #535
Updates the styling of the pininput `input` element to hide the safari yellow background and text colour, which was causing the text to appear twice on iOS browsers.
- Set webkit autofill background to maker bg color
- Set webkit autofill color to transparent
- Rearranged cell to be above input instead of the other way around
> fix(pininput): fix safari autofill styles

- src/components/Textarea/src/TextareaControl.vue
Currently the disabled textarea allows a user to still type inside
Because `disabled` is a prop on the `TextareaControl` it's not included in the `$attrs` and thus not passed into the `textarea` element
> fix(textarea): properly disable textarea

- styleguide/SideNav.vue
Some components are under multiple groups, which when run locally causes these vue warns to occur
Prepend group to the key name to make them unique
> docs: provide unique keys for side nav

- src/components/TextButton/src/TextButton.vue
Properly set the CSS for the disabled state to `not-allowed`
> fix(textbutton): fix cursor css for disabled state

- src/components/Input/src/InputControl.vue
when minputs are very narrow (< 200px width) and had a suffix (text or icon) the suffix would get cut off.
stops suffix from getting cut off with minput is < 200px width
nope
> fix(input): suffix icons getting cut off

- src/components/PinInput/src/PinInputControl.vue
Closes #544
This PR updates the safari autofill styles to hide the yellow background and input text on iOS devices.
> fix(pininput): fix safari autofill styles on mobile

- src/components/Checkbox/src/CheckboxControl.vue
When using keyboard-only to navigate the page, tab controls rely on the outline to show the user where they are focused on the page. `outline: none` on Checkbox essentially removed the `focus` state, making it look like you could not interact with the Checkbox via keyboard controls.
(checkboxes stay the exact same while tabbing through)
Improved accessibility via adding back in outline on checkbox `focus` state.
https://github.com/square/maker/assets/20190589/976b4936-b672-40a6-a27b-91ac9ac1a551
Test the existing experience on the [18.0.5 styleguide](https://square.github.io/maker/styleguide/18.0.5/#/Checkbox):
- click on the description under 'Checkbox' title
- press 'tab' to focus on the links within the description ('Choice', 'Radio', etc.)
- keep pressing 'tab' until you're past the …
> fix(Checkbox): show outline on `focus`

- src/components/Stepper/src/Stepper.vue
Stepper's plus and minus buttons are only described as "button" on screenreader, making it difficult to distinguish between the two and know what they do.
Added `aria-label` to the plus and minus buttons on the Stepper.
Mac VoiceOver reads out as "plus, minus":
https://github.com/square/maker/assets/20190589/1fde59dd-1dbc-4add-8c7f-d30206a7ef27
1. adding screenreader labels on the icon level
While this is something that could be considered in the future to optionally be included by screenreaders, I don't think that all icons, being used as just icons, need to be read out. However, in this case, the icon was being used as the _label_ for a button on the stepper, not just a decorative icon. It's also a much lower-effort addition, since the icon usage here is hard-coded.
2. using the words …
> fix(Stepper): add "+, -" aria-labels 

- src/components/Popover/src/Popover.vue
Doing some memory leak testing and looks like popover poppers weren't being properly destroyed resulting in detached HTML elements.
Digging in there were 2 core issues:
1) `currentPopper` was being accessed in `close` in the actionApi scope instead of the vm scope, so `.destroy()` was never being called on the popper instance.
2) Even if 1) was working correctly, the `close` logic in the actionApi is only triggered if the user clicks the action element (e.g. a button). However, if the user clicks outside to close the popover, the `close` logic was never called and thus the `destroy` logic never called (as `popperToDestroy` is never set)
I don't think there was any need for the logic in `close` for destroying. We can just rely on `m-transition-fade-in @after-leave="destroyPopper"`, because …
> fix(popover): fix destroy logic

- src/components/Icon/src/Icon.vue
- src/components/Theme/src/default-components.cjs
This fixes an icon color bug. Icons with no `color` prop declared are not inheriting the parent color as desired, but inheriting the nearest parent definition of `--color`, which typically happens on the nearest MTheme. This causes a bug on button loaders where instead of applying the button color, it applies the MTheme color instead.
This PR replaces `--color: inherit` with `--color: currentColor`, which fixes the color inheritance bug.
> fix(icon): fix default icon color inheritence

- package-lock.json
- package.json
- src/components/Dialog/README.md
- src/components/Dialog/index.js
- src/components/Dialog/src/DialogLayer.vue
- src/components/Modal/README.md
- src/components/Modal/index.js
- src/components/Modal/src/ModalLayer.vue
- src/components/Popover/README.md
- src/components/Popover/src/PopoverLayer.vue
This PR makes some changes to the modal, dialog, and popover layers to allow initialization of the layers to be done via composables instead of mixins. This is to support components that use the composition API in Vue 2.7.14 (and eventually Vue 3.x).
- Convert modal, dialog, and popover APIs to be able to be initialized by either mixin or composable
- Add documentation for changes
- Require Vue 2.7.14
> feat(modal,dialog,popover)!: add composables for modal/dialog/popover layers

- src/components/Button/src/Button.vue
- src/components/Icon/README.md
Custom hover color on outline and ghost buttons incorrectly applying to the fill color.
https://github.com/square/maker/assets/1486885/a407ce43-2352-43ce-9eaa-07f7f1121a3f
Fixes the hover state for custom hover colors on outline/ghost buttons.
https://github.com/square/maker/assets/1486885/40929af3-db68-4d7a-bec7-23e64afc4463
> fix(button): fix custom hover color style on outline/ghost buttons

- src/components/Text/README.md
- src/components/Text/src/Text.vue
When the text is centered with letter spacing, it isn't center aligned:
Add padding left to balance it out:
> feat(text): balance letter-spacing when centered

- src/components/Image/README.md
- src/components/Image/src/Image.vue
Add hexagon as an image `shape` option
* Implemented using css `clip-path` with an inline svg
* Initially tried implementing this using a shared svg file, but the `clip-path` css property only works with a specific id on `clipPath` which made referencing the file difficult. [Documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) suggests that this can be done with `clip-path: url(hexagon.svg#hexPath)`, but I was not able to get this to work in the same way we would reference `background-image: url(./hexagon.svg)`. I could only get this to work if the referenced svg was visible in the DOM without being conditionally rendered. Referencing svg via file path would also have to add additional webpack loaders.
I also considered appending an svg to the DOM if one is not …
> feat(image): add hexagon as an image shape

- src/components/Dialog/README.md
- src/components/Dialog/src/Dialog.vue
- src/components/Modal/README.md
- src/components/Modal/src/Modal.vue
Closes #565 
Provides a prop to block swiping away dialogs and modals on touch-enabled devices. `closeOnSwipeDown` is enabled by default to maintain current functionality.
- Add `closeOnSwipeDown` as a prop on `MDialog` and `MModal` components
- Update `MDialog`/`MModal` to check the value of `closeOnSwipeDown` to enable/disable swipe (nullish values evaluate to enabled)
> feat(dialog,modal): allow blocking swipe-to-close

- src/components/Image/src/Image.vue
* `clip-path` was being inconsistently applied when there were a lot of images on the page. This was possibly due to the implementation, which was relying on an id attached to the svg to identify the shape. There was likely id collision happening, but utilizing clip path only appeared to work if the id was static, so this PR changes the implementation of `clip-path`
* Switch from using `clip-path: url(#id);` to `clip-path: polygon()`, which consistently applies shape to the image
> fix(image): Change implementation of clip-path for images

- src/components/Image/src/Image.vue
* Image shape `circle` and `arch` were not working without defining an explicit height for the image. This was because the `onLoaded` method being used to set the image `height` and `width` was being triggered in the same update cycle as `loaded`. Because we are using `v-show="loaded"` the element has not yet appeared in the DOM so the `offsetHeight` will always be 0. You can see in the screenshot that the shape is actually applied, once the resize method has been triggered and the element is actually visible.
https://github.com/square/maker/assets/82115556/0d93cbb3-323a-4af5-94c6-04551b95ca4a
* This PR ensures that `offsetHeight` is only retrieved after the DOM has had a chance to update and the image is actually visible
> fix(Image): shape not working without explicit image height

- src/components/Skeleton/src/SkeletonBlock.vue
- src/components/Skeleton/src/SkeletonText.vue
Lighthouse analysis led to recommend using opacity for the skeleton loaders for better performance (https://web.dev/articles/stick-to-compositor-only-properties-and-manage-layer-count).
Anecdotally, testing locally, I did notice an improvement in the animation with less jag using opacity when simulating on our larger sites with a mid-tier mobile device.
Switch to using opacity for the skeleton loaders.
https://github.com/square/maker/assets/18740390/7d2048a7-2456-420a-93dc-08ad308fd8e8
https://github.com/square/maker/assets/18740390/a6178240-7316-4b97-828a-3afd6ade53e9
> fix(skeleton): use opacity instead of background-color

- src/components/Image/src/Image.vue
Safari seems to really struggle with getImageDimensions, specifically calling offsetHeight/offsetWidth which triggers a style recalculation. If you're scrolling a list that has images (e.g. OO on mobile view), it just causes the main thread to get frozen.
Try to preload the image dimensions in the mounted event instead of waiting of the onLoaded event which can cause the main thread to freeze for a significant amount of time.
Also added logic to just skip getting the image dimensions if the shape is square.
> perf(image): scrolling large number of images in Safari

- src/components/Image/src/Image.vue
Used `||` instead of `&&` on the shouldGetImageDimensions
> fix(image): wrong condition on shouldGetImageDimensions

- src/components/Image/src/Image.vue
Noticed on our OO sites in Safari removing the images vastly improved the scroll experience. From there it was just removing attributes and CSS until I narrowed it down to the `height: 100%` seemingly causing the issue. Will see if the deployed version provides the same perf gain.
Use `inherit` instead of `100%` and remove the parent `span` as that causes perf issues. `img` needs to be a direct child of the `div`.
> perf(image): update css for perf on safari

- src/components/Button/src/Button.vue
The `information` slot in `MButton` currently uses a `width` property inside a flex container, which causes the text to be cut off in situations where the main slot runs long.
This PR changes the slot to be sized with `flex` properties, specifically setting the `flex-basis` so that contents aren't elided.
> refactor: adjust sizing of MButton info slot

- src/components/Image/src/Image.vue
Still trying to narrow down a fix for the Safari scroll issues.
Using overrides in Safari, setting a static height/width style on the images after they render seems to solve the perf issue. Tested on a photo layout site to ensure the images resize properly switching between desktop/mobile. Will only enable this prop for Safari.
> perf(image): use static size styles for safari

- src/components/Icon/src/Icon.vue
- src/components/Image/README.md
- src/components/Toast/README.md
- src/components/Toast/src/Toast.vue
- src/utils/constants.js
The `MToast` component uses an `MIcon` component under the hood. Since the default size for `MIcon` is `small`, all of the toast icons are also small.
Added an `icon-size` property to allow devs to control the size of the toast icons.
Example with `icon-size="medium"`
*Before:*
*After:*
> feat(toast): add icon size prop

- src/components/Theme/README.md
- src/components/Theme/src/default-colors.cjs
- src/utils/maker-colors.js
The color `neutral-20` generated by the maker colors utility did not pass minimum (3:1) contrast requirements in the components it's used on (input borders, toggle buttons etc).
This PR adjusts the values used to generate `neutral-20` so that components using it in their styles pass contrast requirements for accessibility. This PR also updates the README for theme so that it uses the makerColors utility functions to demo the colors and includes their contrast values.
> feat(a11y): update maker neutral-20 to meet contrast requirements
