lab/create-router.js

The `Laboratory` component allowed customizing all these random "theme variables" none of which the library actually supports yet so it was screwing up the styles of random components in the `KitchenSink` experiment.
- remove `Laboratory` from base Lab view, it wasn't doing anything useful
no

fix: weird hover styles in KitchenSink lab

---

README.md
styleguide/Landing.vue
styleguide/create-router.js

small quality of life improvement

docs: make docs homepage same as github repo readme

---

package-lock.json
package.json
src/components/SegmentedControl/README.md
src/components/SegmentedControl/index.js
src/components/SegmentedControl/src/Segment.vue
src/components/SegmentedControl/src/SegmentedControl.vue
src/components/SegmentedControl/src/key.js

no segmented control component
adds segmented control component
https://square.github.io/maker/styleguide/segmented-control/#/SegmentedControl
nope

feat: mvp SegmentedControl component

---

package-lock.json
package.json
src/components/SegmentedControl/README.md
src/components/SegmentedControl/src/SegmentedControl.vue

Torch subslot

---

src/components/SegmentedControl/src/Segment.vue
src/components/SegmentedControl/src/SegmentedControl.vue

minor design fixes
https://square.github.io/maker/styleguide/segcon-design-fixes/#/SegmentedControl

fix: segcon sizing

---

package.json
src/components/ActionBar/src/ActionBarButton.vue
src/components/Button/src/Button.vue
src/components/Heading/src/Heading.vue
src/components/Input/src/InputControl.vue
src/components/Notice/src/Notice.vue
src/components/Section/src/Section.vue
src/components/SegmentedControl/src/Segment.vue
src/components/Select/src/SelectControl.vue
src/components/Stepper/src/Stepper.vue
src/components/Text/src/Text.vue
src/components/Textarea/src/TextareaControl.vue
src/utils/InlineFormControlLayout/src/InlineFormControlLayout.vue

refactor: components inherit font-family

---

package.json
src/components/Input/src/InputControl.vue

default input, filled variant, has tiny visible border
removes tiny visible border

fix: filled input border

---

package.json
src/components/SegmentedControl/src/Segment.vue

Requests made by Derick: https://docs.google.com/spreadsheets/d/1m4E4X-Sg6r73ajSQ_aC7CdZyxbnaS9mk8kXnhvNTzhQ/edit#gid=0 lines 18 and 31
- Set unselected segment text color to black alpha 60, and selected text color to full black.
- Added a slight drop shadow to selected segment to give slight elevation and separation

style: update segmented control styles

---

package.json
src/components/Input/README.md
src/components/Input/src/InputControl.vue

adds `outline` variant to minput
https://square.github.io/maker/styleguide/outline-input/#/Input

feat: adds outline variant to minput

---

package.json
src/components/Textarea/README.md
src/components/Textarea/src/TextareaControl.vue

outline variant for Textarea
https://square.github.io/maker/styleguide/outline-textarea/#/Textarea
nope

feat: Outline variant for MTextarea

---

build/checkout-master/index.js
package.json

a script to automate publishing/releasing to NPM (as well as building & publishing lab & styleguide)
I'm pretty sure it works but haven't done any real tests yet
I'm gonna wait until the next PR gets merged into master and then try running it then, and if it's success I'll merge this in

chore: Publish script

---

package-lock.json
package.json
src/components/ActionBar/src/ActionBarLayer.vue
src/components/ActionBar/src/AtomicActionBar.vue
src/components/ActionBar/src/InlineActionBar.vue

fix: dead-click on ios safari for actionbar

---

package.json
src/components/ActionBar/src/ActionBarButton.vue

Action bar buttons loading state causes corners to appear on the action bar
Added a border radius to the loading state so corners are no longer visible.

fix: add border radius to loading state so rounded button doesnt have corners

---

package.json
src/components/Choice/README.md
src/components/Choice/index.js
src/components/Choice/src/Choice.vue
src/components/Choice/src/ChoiceOption.vue
src/components/Choice/src/key.js

Created choice component that allows to select a single option or multiple options
https://square.github.io/maker/styleguide/choice-component/#/Choice

feat: Add choice component

---

src/components/Calendar/README.md
src/components/Calendar/src/Calendar.vue

PR review for https://github.com/square/maker/pull/41
Specific changes commented inline.
Size change: `62.3 kB` -> [`15.4 kB`](https://github.com/square/maker/pull/49)
@pretzelhammer :
- Highly recommend adding tests for stuff like this
- I corrected JSDoc pretty seriously here. It's pretty helpful when using VueDX. What do you think about linting them so they're correctly used?
Side note:
- The button styles on active state behaves a little strange to me. When holding the mouse down for a second too long, the border shows up and disappears. Is this expected?

review(calendar): review changes

---

package-lock.json
package.json

- Should not have a hardcoded version. It's automatically managed by semantic-release.
- Replace `package.json` with the semantic-release placeholder

chore: semantic release placeholder version

---

.github/workflows/lint-pr-title.yml
build/webpack-build-config.js
lab/webpack-lab-config.js
package-lock.json
package.json
styleguide/webpack-styleguide-config.js

- Race condition that deletes `transitions.js`
- Remove `clean-webpack-plugin`
- Closes https://github.com/square/maker/issues/55

fix: remove clean-webpack-plugin

---

.github/PULL_REQUEST_TEMPLATE.md

Examples only showed what to do, didn't clarify what not to do. In particular, inserting a ticket name in square-brackets seems to break GitHub's PR title to commit message conversion.
Add Dos and donts in PR template

docs(pr template): improve examples with dos and donts

---

src/components/ActionBar/src/ActionBarLayer.vue
src/components/ActionBar/src/AtomicActionBar.vue

https://github.com/square/maker/issues/62
nope

fix: removes gradient bg on actionbar

---

.eslintrc.js
.github/workflows/lint-code.yml
package.json

Strangely, [airbnb-base allowed magic-numbers](https://github.com/airbnb/javascript/blob/1fb4592122ef94029b3ff2f361408f0681751253/packages/eslint-config-airbnb-base/rules/best-practices.js#L185). This means you can use arbitrary numbers without explaining what they mean via variable name.
- Disallow magic number via warning until codebase is clean
- Remove `src` from the lint-staged filter. There are linting errors in other directories.
- Once codebase is clean, replace `src lab styleguide build` with `.` in the `lint:js` script
<details>
<summary>Current violations</summary>
```
> eslint --format=pretty --ext vue,js,md --max-warnings=0 --cache src lab styleguide build
src/components/Heading/src/Heading.vue:17:33
⚠   17:33  No magic number: -2.                           no-magic-numbers
⚠ …
```

style: disallow magic numbers

---

.eslintrc.js

chore(lint): removes bad lint rule

---

build/generate-readme-api-tables/index.js
build/sync-to-latest/index.js
build/utils.js
build/webpack-build-config.js
lab/Landing.vue
lab/experiments/Button.vue
lab/experiments/SiteApp/ItemModal.vue
lab/experiments/SiteApp/index.vue
src/components/ActionBar/src/ActionBarButton.vue
src/components/ActionBar/src/ActionBarLayer.vue
src/components/Button/src/Button.vue
src/components/Calendar/README.md
src/components/Calendar/src/Calendar.vue
src/components/Choice/src/ChoiceOption.vue
src/components/Heading/src/Heading.vue
src/components/Stepper/src/Stepper.vue
src/components/Text/src/Text.vue
src/components/TransitionFadeIn/README.md
src/components/TransitionResize/src/TransitionResize.vue
src/components/TransitionSpringLeft/README.md
src/components/TransitionSpringUp/README.md
src/utils/Transition/README.md
src/utils/TransitionResponsive/README.md
src/utils/TransitionResponsive/src/TransitionResponsive.vue
src/utils/transitions.js

chore: lint fixes

---

src/components/ActionBar/src/ActionBarButton.vue

fix(actionbar): make actionbar buttons medium size on all resolutions

---

src/components/ActionBar/README.md
src/components/ActionBar/src/ActionBarButton.vue

adds shapes to actionbar buttons
adds shapes to actionbar buttons
adds shapes to actionbar buttons

feat(actionbarbutton): pill, rounded, & squared shapes

---

build/webpack-base-config.js
build/webpack-build-config.js
lab/experiments/ActionBarTest.vue
lab/webpack-lab-config.js
styleguide/webpack-styleguide-config.js

- Webpack build config had unnecessary complications
- Moved minifier/optimization plugins to base config so it can be shared by all configs
- Improved build config simplicity & readability

build: refactor webpack configs

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml

It's currently easy to overlook that this is a public repo, and risk contributors to inadvertently share sensitive info.
- Add a warning sign at the top of the issue template to remind our contributors.
- It's currently not easy to preview these changes unless merged, so might iterate on it post-merge.

chore: add public repo warning to issue templates

---

.github/CODEOWNERS

CODEOWNERS file specified individuals. Now there is a core team that is dynamic: https://github.com/orgs/square/teams/maker-core-contributors/members
Update CODEOWNERS to use the core team handle

chore: codeowners to use new core team

---

src/components/ActionBar/src/ActionBarButton.vue
src/components/Button/src/Button.vue
src/components/Theme/README.md
src/components/Theme/index.js
src/components/Theme/src/utils.js

makes code more DRY
makes code more DRY
nope

refactor(theme): drier themeable props

---

src/components/Theme/README.md
src/components/Theme/src/Theme.vue
src/components/Theme/src/default-theme.js

adds theme-level profiles
adds theme level profiles
visit https://square.github.io/maker/styleguide/theme-level-profiles/#/Theme and scroll down to the **Customizing the theme within subsets of the app** section.

feat(theme): theme level profiles

---

src/components/Popover/README.md

Updated some docs in the new popover component
1. Added a simpler first example. (Easier to copy+paste)
2. Removed the very custom example. Not realistic real-world example. The existing demos show what's more typical.

chore(popover): add basic demo, remove padding from readme

---

.github/workflows/deploy-styleguide.yml
.github/workflows/lint-code.yml
.github/workflows/release.yml

Github Actions reinstalled dependencies from registry each time when it could be cached.
Cache npm cache across GitHub actions.
Actions:
- [Deploy Styleguide - uncached](https://github.com/square/maker/actions/runs/1523109576) - 1m 54s
- [Deploy Styleguide - cached](https://github.com/square/maker/actions/runs/1523120779) - 1m 29s (Saved 25s)
Will take more samples once this can be against master.

ci: cache npm dependencies

---

src/components/Text/src/Text.vue

Line height in paragraph missing
Fixed typo

fix(text): typo in line height

---

.postcssrc.js
src/components/ActionBar/src/ActionBarLayer.vue
src/components/ActionBar/src/AtomicActionBar.vue
src/components/Blade/src/Blade.vue
src/components/Dialog/src/Dialog.vue
src/components/Dialog/src/DialogLayer.vue
src/components/Heading/src/Heading.vue
src/components/Modal/src/Modal.vue
src/components/Modal/src/ModalLayer.vue
src/components/Text/src/Text.vue
src/styles/breakpoints.css

Partial solution for issue #39 - specifically addressing standardizing breakpoints across components with custom media queries.

build(breakpoints): define breakpoints as custom media queries

---

lab/experiments/FluidScale.vue
src/components/Heading/README.md
src/components/Heading/src/Heading.vue
src/components/Text/README.md
src/components/Text/src/Text.vue
src/components/Theme/src/Theme.vue
src/components/Theme/src/default-theme.js

no theming typography
yes theming typography
[MHeading docs](https://square.github.io/maker/styleguide/theming-typo-website-compat/#/Heading)
[MText docs](https://square.github.io/maker/styleguide/theming-typo-website-compat/#/Text)

feat!: theming typography compatible with Website

---

src/components/Text/src/Text.vue

we got feedback from Website that mtext should support `li` tags
mtext now supports `li` tags
no

feat(text): support li tags

---

src/components/Heading/src/Heading.vue
src/components/Text/src/Text.vue

no prop to italicize text (needed for website)
adds `fontStyle` prop to MText and MHeading which accepts `inherit`, `normal`, and `italic` values
nope

feat: font style prop to italicize text

---

src/components/Text/README.md
src/components/Text/src/Text.vue

for Website, need `div` tag for texts
adds `'div'` to Text component `tag` prop validator
nope

feat(text): adds support for div tags

---

src/components/Text/README.md
src/components/Text/src/Text.vue

revert: "feat(text): add support for all text sizes"

---

src/components/Text/README.md
src/components/Text/src/Text.vue

We had to rewrite some history. This gets us back to where we wanted to be with a v9.1 release.

fix: add missing Text feature from rebase

---

src/components/Heading/src/Heading.vue
src/components/Text/src/Text.vue

asked for by Website
updates `color` prop validators in MText & MHeading to be more permissible
nope

feat: support more color values for MText & MHeading

---

src/components/Blade/src/Blade.vue
src/components/Dialog/src/Dialog.vue
src/components/Dialog/src/DialogLayer.vue
src/components/Modal/src/Modal.vue

https://github.com/square/maker/issues/257
changes `overflow: scroll` to `overflow: auto` and does small refactor in Dialog to fix other small issues that crept in that we didn't notice earlier.
nope

fix: double scrollbars on Dialog, Modal, Blade

---

.github/workflows/release.yml

once we make a major release there's no automated way for backporting features or bugfixes to prior major releases
adds `'[1-9][0-9]*.x'` to the `branches` config of our `release` action which should now run semantic-release on any pushes to branches that match that regex pattern, e.g. `8.x`, `9.x`, `10.x` etc
- github docs on branch filtering syntax (which is not regex but is close to it): https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
- semantic release docs on publishing maintenance releases: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/release-workflow/maintenance-releases.md

ci: run semantic release on maintanence releases

---

src/components/Blade/src/Blade.vue
src/components/Dialog/src/Dialog.vue
src/components/Dialog/src/DialogLayer.vue
src/components/Modal/src/Modal.vue

Experimenting with backporting bug fixes to older major versions. This code has already been merged and released for v9 but I'm backporting it to v8.
fixes double scrollbars for v8
nope

fix: double scrollbars on Dialog, Modal, Blade (#273)

---

lab/experiments/Themes/index.vue
lab/experiments/Themes/preview.vue
lab/experiments/Themes/themes.js

merging `master` into `beta` broke landon's advanced theming lab demo since it was still using mheadings (which were removed in `beta`) so this pr updates the lab so it works with mtexts only (now using the `title` variant)
just did
nope

docs: fix headings in beta advanced lab demo

---

lab/experiments/ThemeTest.vue

adds typography controls to lauren's excellent theme lab
same as above
https://square.github.io/maker/lab/theme-lab-typo-controls/#/ThemeTest

docs: theme lab typo controls

---

lab/experiments/ThemeTest.vue
src/components/Theme/src/default-theme.js

Shimaa clarified/updated what the defaults for headline, title, paragraphs, and labels should be.
updates defaul theming data for typography stuff
no

fix!: typography defaults

---

lab/experiments/ThemeTest.vue
src/components/Theme/src/utils.js

fix(theme): 0 values now resolve correctly

---

src/components/Theme/src/default-theme.js

fix(stepper): stepper buttons not rendering, textColor cannot be inherit

---

src/components/Input/README.md
src/components/Input/src/InputFormItem.vue

Added `focus()` and `blur()` methods to input component.

feat(input): add focus and blur methods to input

---

.github/workflows/deploy-styleguide-lab.yml
.github/workflows/release.yml
.github/workflows/remove-styleguide-lab.yml
README.md
build/generate-deploy-index/index.js
build/log-ci-info.js
build/sync-to-latest/index.js
build/utils.js
lab/webpack-lab-config.js
styleguide/webpack-styleguide-config.js

ci: more improvements

---

src/components/Image/README.md
src/components/Theme/src/default-theme.js

fix(notice): standalone prop should work as expected

---

src/components/Theme/src/default-theme.js

#341 
Let's not beat a dead horse in the mouth here

fix(theme): make Headline fontWeight use fontWeight value

---

src/components/Image/src/Image.vue

Currently, the image loading skeleton does not get the shape classes or styles
Fixes above issue with image skeletons

fix(image): Apply image shape styles to skeleton as well

---

src/components/Image/src/Image.vue

We need to check that an observer exists before trying to unwatch image element in the `beforeDestroy` hook.
Adds the check described.

fix(image): fix image observer for non-lazyload images

---

lab/experiments/Themes/index.vue
lab/experiments/Themes/preview.vue
lab/experiments/Themes/themes.js

There were several issues with the theme lab, mostly around the profiles, contrast logic, default fonts, and preview height.
Before:
https://square.github.io/maker/lab/latest-stable/#/Themes/
Try changing the background on a profile from light to dark.
I fixed it so it would work as expected.

docs: fixes for theme lab demo

---

.github/CONTRIBUTING.md

docs: backporting features & bugfixes

---

lab/experiments/ThemeTest.vue
src/components/Button/README.md
src/components/Link/README.md
src/components/Link/index.js
src/components/Link/src/Link.vue
src/components/TextButton/README.md
src/components/TextButton/src/TextButton.vue
src/components/Theme/src/default-theme.js
styleguide/create-router.js

closes https://github.com/square/maker/issues/357
adds mvp link component, it works with basic hrefs and also within vue router contexts
[styleguide link docs](https://square.github.io/maker/styleguide/mvp-link/#/Link)
[themetest lab with links](https://square.github.io/maker/lab/mvp-link/#/ThemeTest)

feat(link): link component

---

src/components/Calendar/src/Calendar.vue
src/components/Icon/README.md
src/components/Icon/src/Icon.vue
src/components/Image/README.md
src/components/Select/src/SelectControl.vue
src/components/Theme/src/default-icons.js

no themeable icons in calendar or select
adds themeable chevron icons to maker. also adds `size` prop to MIcon.
nope

feat: themeable chevron icons

---

src/components/Accordion/README.md
src/components/Accordion/index.js
src/components/Accordion/src/Accordion.vue
src/utils/Row/README.md
src/utils/Row/src/Row.vue

closes https://github.com/square/maker/issues/356
implements accordion component
https://square.github.io/maker/styleguide/mvp-accordion/#/Accordion

feat(accordion): mvp accordion component

---

src/components/Theme/src/default-theme.js

closes https://github.com/square/maker/issues/391
fix(choice): defaults selected color to primary color
nope

fix(choice): defaults selected color to primary color

---

src/components/Button/README.md

improves button docs
improves button docs

docs: improves button docs

---

src/components/Dialog/README.md
src/components/Dialog/src/DialogLayer.vue
src/components/Modal/README.md
src/components/Modal/src/ModalLayer.vue

closes https://github.com/square/maker/issues/399
adds `closeOnEsc` option to `dialogApi.open({ options })` and `modalApi.open({ options })`
nope

feat: close on esc added to dialog & modal

---

src/components/ProgressCircle/README.md
src/components/ProgressCircle/index.js
src/components/ProgressCircle/src/ProgressCircle.vue
src/components/Theme/src/default-theme.js

no progress circle
adds progress circle
https://square.github.io/maker/styleguide/mvp-progress-circle/#/ProgressCircle

feat: mvp progress circle component

---

lab/experiments/ButtonTruncation.vue
src/components/Button/src/Button.vue

Currently, Button does not have the same text truncation styles as ActionbarButton
Adds truncation styles for Button

feat(button): apply trunctation styles

---

src/components/Divider/README.md
src/components/Image/README.md
src/components/ProgressBar/README.md
src/components/VerticalDivider/README.md
src/components/VerticalDivider/index.js
src/components/VerticalDivider/src/VerticalDivider.vue

no vertical divider
adds vertical divider
https://square.github.io/maker/styleguide/vert-divider/#/VerticalDivider

feat: mvp vertical divider component

---

src/components/Button/README.md
src/components/Theme/src/default-theme.js

Buttons do not have contextual color patterns
Adds contextual color patterns for buttons

feat(button): add contextual color patterns, update docs

---

src/components/ProgressBar/README.md
src/components/ProgressBar/src/ProgressBar.vue
src/components/ProgressCircle/README.md
src/components/ProgressCircle/src/ProgressCircle.vue

no aria labels on progress components
adds aria labels to progress components
nope

fix: adds aria labels to progressbar & progresscircle

---

lab/components/ActionBarBlade.vue
lab/components/ActionBarDialog.vue
lab/components/ActionBarModal.vue
lab/components/NestedModal.vue
lab/experiments/ReactiveLayerProps.vue
src/components/Blade/src/BladeLayer.vue
src/components/Dialog/src/DialogLayer.vue
src/components/Modal/src/ModalLayer.vue
src/utils/RenderFn.js

closes https://github.com/square/maker/issues/143
internal refactors in bladelayer, modallayer, and dialoglayer
- [ReactiveLayerProps Lab](https://square.github.io/maker/lab/reactive-layer-props/#/ReactiveLayerProps)
- [Blade styleguide](https://square.github.io/maker/styleguide/reactive-layer-props/#/Blade) (no changes)
- [Dialog styleguide](https://square.github.io/maker/styleguide/reactive-layer-props/#/Dialog) (no changes)
- [Modal styleguide](https://square.github.io/maker/styleguide/reactive-layer-props/#/Modal) (no changes)

fix: reactive layer props

---

src/components/TextButton/README.md
src/components/Theme/src/default-theme.js

Textbutton patterns are not documented and do not include a contextual `primary` pattern.
Adds a `primary` pattern for Textbutton, updates docs to list all available patterns.

feat(textbutton): add primary pattern to text button, update docs

---

src/components/StarRating/README.md
src/components/StarRating/src/StarRating.vue

stars weren't rendering in user's apps
should make stars render now, i think there's an issue with the recursive absolute import statements
will use my admin perms to merge this without a review since Lauren is out today

fix(starrating): make recursive absolute import into a relative import

---

src/components/Button/README.md
src/components/Theme/src/default-theme.js

`pattern="fill`, `pattern="outline"`, `pattern="ghost"` were the same as `variant="fill"`,  `variant="outline"`,  `variant="ghost"`. Missing contextual color patterns for `variant="ghost"` buttons.
Removes redundant patterns, adds contextual color patterns for ghost buttons.

refactor(button)!: clean up patterns, add ghost patterns

---

.github/workflows/deploy-styleguide-lab.yml
.github/workflows/release.yml
.github/workflows/remove-styleguide-lab.yml
build/deploys/pull.js
build/deploys/push.js
build/generate-deploy-index/index.js
package.json
styleguide/INDEX.md

taking this already approved PR https://github.com/square/maker/pull/443 and backporting it to the 14.x line (when i originally made the 14.x branch i overlooked this commit which should have been included, so i'm adding it now)

ci: increase deploy styleguide & lab job success rate (#443)

---

src/components/Image/src/Image.vue

closes https://github.com/square/maker/issues/457
places `src` below `srcset` and `sizes`
nope

fix(image): relative src, sizes, & srcset attribute ordering

---

src/components/PinInput/README.md
src/components/PinInput/src/PinInputControl.vue

fix(pininput): support browser autofill behavior

---

.github/workflows/lint-code.yml
.github/workflows/lint-pr-title.yml
.github/workflows/package-size-report.yml

we weren't running the lint code action on PRs which required the lint code action to run and complete in order to be merged
adds relevant configs to workflow files to run the actions for the right branches
nope

ci: add required actions to protected release branches

---

.github/CODEOWNERS
src/components/PinInput/README.md
src/components/PinInput/src/PinInputControl.vue

Updates to Maker team structure.
New structure allows more people to approve more PRs.
Before a Maker Core Team member would have to approve any PR before it could get merged.
A new group of people, called Maker Reviewers, can now approve PRs which change components, lab experiments, or docs and those PRs can be merged without approval from a Maker Core Team member.
The teams referenced in the code comments can be found here:
- maker contributors: https://github.com/orgs/square/teams/maker-contributors/members
- maker reviewers: https://github.com/orgs/square/teams/maker-reviewers/members
- maker core team: https://github.com/orgs/square/teams/maker-core-team/members
Maker Core Team is a child team of Maker Reviewers, so all Maker Core Team members are also reviewers. Maker Reviewers are …

chore: update github codeowners

---

lab/experiments/ButtonCustomization.vue
src/components/Button/README.md
src/components/Button/src/Button.vue
src/components/Text/src/Text.vue
src/components/Theme/src/default-theme.js

Buttons currently do not support custom border, box-shadow, shape, text, and hover styles.
Adds support to buttons for custom border, box-shadow, shape, text, and hover styles

feat(button): add props for border, box-shadow, shape, text, and hover styles

---

.github/workflows/stale.yml
src/components/Link/README.md

broken link in MLink docs
no more broken link
nope

docs: fixes broken link in MLink docs

---

src/components/Choice/src/Choice.vue
src/components/Choice/src/ChoiceCard.vue
src/components/Choice/src/ChoiceOption.vue

i thought the choice disabled color looked weird
i fixed it... unless I'm missing something
before:
after:

fix(choice): disabled text color

---

.github/workflows/release.yml

Outdated `semantic-release`.
Upgrade to latest `semantic-release` v19.

ci: upgrade semantic-release

---

.eslintrc.js
package.json

Previously, the eslint command was:
- specifying which directories to lint instead of the entire project
- needlessly specifying file extensions. These are set via "overrides".
ESLint to lint entire project and ignore distribution directories.

chore: refactor eslint command

---

src/components/Button/README.md
src/components/Button/src/Button.vue

Buttons don't support anchor tags styled like buttons, a very common web convention.
Adds `tag` prop to MButton to allow them to render anchor tags instead of buttons for links.

feat(button): add anchor tag option

---

src/components/Calendar/src/Calendar.vue

fix(calendar): bad contrast when primary & bg color too similar

---

src/components/Thumbnails/README.md
src/components/Thumbnails/index.js
src/components/Thumbnails/src/Thumbnails.vue

We need a component to display list of images with overflow text displayed when hitting the max thumbnail count. See desgins - [Figma](https://www.figma.com/file/kmUoROmFpcprMw7xW2YIT9/Subscriptions-in-Customer-Accounts-%E3%83%BC-Buyer-%E2%80%94-Erin-%E2%80%94-Q322?node-id=7699%3A29177)
Added a thumbnails component

feat(thumbnails): add Thumbnails component

---

.github/MIGRATION.md
lab/experiments/ThemeTest.vue
lab/experiments/Toasts/index.vue
src/components/Checkbox/src/CheckboxControl.vue
src/components/Icon/README.md
src/components/Input/src/InputControl.vue
src/components/Notice/src/Notice.vue
src/components/PinInput/src/PinInputControl.vue
src/components/ProgressCircle/README.md
src/components/Radio/src/RadioControl.vue
src/components/Select/src/SelectControl.vue
src/components/Textarea/src/TextareaControl.vue
src/components/Theme/src/default-colors.cjs
src/components/Theme/src/default-components.cjs
src/components/Theme/src/default-icons.cjs
src/components/Theme/src/publicize-vars.cjs
src/components/Toast/README.md
src/components/Toggle/src/ToggleControl.vue
src/utils/maker-colors.js

we use `critical` and `error` interchangeably internally & publically and it's confusing when to use one over the other so we're simplifying this by standardizing on `error` for all situations.
renames all instances of `critical` and `error`
nope

refactor!: rename critical to error

---

src/components/ActionBar/src/ActionBarButton.vue
src/components/Badge/src/Badge.vue
src/components/Button/src/Button.vue
src/components/Calendar/src/Calendar.vue
src/components/Choice/src/Choice.vue
src/components/Link/src/Link.vue
src/components/Pill/src/Pill.vue
src/components/ProgressBar/src/ProgressBar.vue
src/components/Row/src/Row.vue
src/components/SegmentedControl/src/SegmentedControl.vue
src/components/Stepper/src/Stepper.vue
src/components/TextButton/src/TextButton.vue
src/components/Toast/src/Bread.vue
src/components/Toast/src/Toast.vue

overlooked a bunch during initial refactor pr, noticed them just now, finishes refactor
finishes refactor
nope

refactor: use simple vars everywhere

---

src/components/TextButton/src/TextButton.vue

Long words aren't properly truncated with the `truncate-text` prop
Add the overflow-wrap property

fix(textbutton): add overflow wrap

---

src/components/Icon/README.md
src/components/Icon/src/Icon.vue
src/components/ProgressBar/README.md
src/components/ProgressCircle/README.md
src/components/SegmentedControl/README.md
src/components/Theme/src/default-components.cjs
src/components/VerticalDivider/README.md

no patterns for Icon, ProgressBar, or ProgressCircle
adds patterns for Icon, ProgressBar, ProgressCircle
updated styleguides:
- [icon](https://square.github.io/maker/styleguide/more-contextual-patterns/#/Icon)
- [progressbar](https://square.github.io/maker/styleguide/more-contextual-patterns/#/ProgressBar)
- [progresscircle](https://square.github.io/maker/styleguide/more-contextual-patterns/#/ProgressCircle)

feat: contextual patterns for Icon, ProgressBar, & ProgressCircle

---

src/components/Image/src/Image.vue

With the latest release version, image loading has a few snags. This is especially apparent in Safari, where the user agent frequently loads two or more of the images. In my example case, I have an `MImage` with `src`, `srcset`, and `sizes` all set, which causes Safari to load two images from the `srcset` in two resolutions. Additionally, the internal cache inside `MImage` creates an `<image>` tag that loads its `src`, meaning that every image on the page is loading three separate copies of the same image at different resolutions. This has a huge impact in page load performance, as the number of in-flight requests as well as the amount of data loaded can become quite significant on image-heavy pages.
You can observe this in Safari's network tab using the "group by resource" option. Here, …

refactor(image): improve Image loading

---

src/components/Icon/README.md
src/components/Menu/src/MenuOption.vue
src/components/SegmentedControl/README.md
src/components/Stepper/src/Stepper.vue
src/components/Theme/src/default-icons.cjs

icons in Stepper and Menu were not themable
they are now themable
updated icon styleguide: https://square.github.io/maker/styleguide/more-themable-icons/#/Icon

feat: makes icons in Stepper & Menu themable

---

src/components/Theme/src/Theme.vue

This PR allows listeners to be attached to the `Theme` component, closes #513 
Allow listeners to pass through to the `Theme` component

fix(theme): allow listeners

---

src/components/BlockFormControlLayout/src/BlockFormControlLayout.vue
src/components/ImageUploader/src/ImageSelection.vue
src/components/Theme/src/Theme.vue

overlooked some error color places during original pr
fixed overlooked places, also now binding attrs for theme component (similar to how every other component works)
nope

fix: more contextual error colors

---

src/components/PinInput/src/PinInputControl.vue

`replaceAll` doesn't work on Safari 12
changes `replaceAll` to `replace`
nope

fix: refactor for more browser compat

---

.github/workflows/package-size-report.yml

it's not working and failing on every pr, let's remove it for now until it's fixed and we can add it back
disables/removes pkg size check for now
nope

docs: adds comment to disabled broken pkg size check for now

---

package-lock.json
package.json
src/components/Icon/README.md
src/components/Loading/src/Loading.vue
src/components/Theme/src/default-icons.cjs

Loading component wasn't themable, would look the same across all sites/themes.
Makes Loading component themable. It now pulls its spinner icon from the `spinner` key in the `icons` object within the theme config object. this allows people to customize the loading spinner via the Theme component.
not yet

feat: themable loading

---

src/components/Icon/src/Icon.vue

an error being thrown in this edge case is a bit harsh as it can break/crash an app when it's not that big of a deal
emit a warning instead, and fallback to rendering `info` icon instead
nope

fix(icon): fail gracefully if icon not defined in theme

---

src/components/Text/src/Text.vue

`lineHeight` and `letterSpacing` were not themeable.
Make `lineHeight` and `letterSpacing` themeable.

feat(text): themeable `lineHeight` and `letterSpacing`

---

src/components/Text/src/Text.vue

The letterSpacing was only using the prop.
The letterSpacing should use what's resolved via theme.

fix(text): inherit letter spacing from theme

---

src/components/Button/src/Button.vue

Letter spacing was not supported on Buttons
Add support for letter spacing in Buttons

feat(button): support letter spacing
